[package]
name = "oxidebot"
version = "0.1.7"
edition = "2021"
description = "A lightweight yet powerful chatbot framework"
license = "MIT OR Apache-2.0"
authors = ["canxin121 <q1969730106@gmail.com>"]
homepage = "https://github.com/canxin121/oxidebot"
repository = "https://github.com/canxin121/oxidebot"
readme = "Readme.md"
keywords = ["bot", "chatbot", "oxidebot"]
categories = ["science::robotics", "api-bindings"]

[dependencies]
anyhow = "1.0.104"
async-trait = "0.1.91"
chrono = "0.4.45"
hyper = "1.11.0"
mime = "0.3.17"
mime_guess = "2.0.5"
reqwest = { version = "0.13.4", default-features = false, features = [
    "rustls",
] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
tracing = "0.1.44"
url = "2.5.8"
