//! Recursive command-grammar branch definitions.

use super::*;

/// A true node in the command grammar. Unlike a Web route mount, this models
/// user-visible subcommand syntax and is reused by parsing, help, completion,
/// and native command publication.
#[derive(Clone, Debug)]
pub struct CommandBranch {
    pub(in crate::command) id: CommandNodeId,
    pub(in crate::command) name: Arc<str>,
    pub(in crate::command) description: LocalizedText,
    pub(in crate::command) aliases: Vec<Arc<str>>,
    pub(in crate::command) schema: Option<CommandSchema>,
    pub(in crate::command) children: Vec<CommandBranch>,
    pub(in crate::command) completion: Option<CompletionConfig>,
    pub(in crate::command) hidden: bool,
}

impl CommandBranch {
    /// Creates a subcommand grammar node named `name`.
    #[must_use]
    pub fn new(name: impl Into<Arc<str>>) -> Self {
        let name = name.into();
        Self {
            id: CommandNodeId(stable_hash(name.as_bytes()) as u32),
            name,
            description: LocalizedText::default(),
            aliases: Vec::new(),
            schema: None,
            children: Vec::new(),
            completion: None,
            hidden: false,
        }
    }

    /// Sets the default localized branch description.
    #[must_use]
    pub fn description(mut self, description: impl Into<LocalizedText>) -> Self {
        self.description = description.into();
        self
    }

    /// Adds a locale-specific branch description.
    #[must_use]
    pub fn description_translation(
        mut self,
        locale: impl Into<Arc<str>>,
        description: impl Into<Arc<str>>,
    ) -> Self {
        self.description = self.description.translation(locale, description);
        self
    }

    /// Adds an alternative branch name for parsing.
    #[must_use]
    pub fn alias(mut self, alias: impl Into<Arc<str>>) -> Self {
        self.aliases.push(alias.into());
        self
    }

    /// Attaches an argument schema to this branch.
    #[must_use]
    pub fn schema(mut self, mut schema: CommandSchema) -> Self {
        schema.rebase(&self.name);
        self.schema = Some(schema);
        self
    }

    /// Attaches the schema generated by `CommandArgs`.
    #[must_use]
    pub fn args<T: CommandArgs>(self) -> Self {
        self.schema(T::schema())
    }

    /// Adds a nested user-visible subcommand branch.
    #[must_use]
    pub fn subcommand(mut self, mut branch: CommandBranch) -> Self {
        branch.rebase(&format!("{}.{}", self.name, branch.name));
        self.children.push(branch);
        self
    }

    /// Enables interactive recovery for missing required arguments on this branch.
    #[must_use]
    pub fn completion(mut self, completion: CompletionConfig) -> Self {
        self.completion = Some(completion);
        self
    }

    /// Hides this branch from help and completion while retaining parse support.
    #[must_use]
    pub const fn hidden(mut self) -> Self {
        self.hidden = true;
        self
    }

    /// Returns this branch's stable grammar-node ID.
    #[must_use]
    pub const fn id(&self) -> CommandNodeId {
        self.id
    }

    /// Returns the canonical branch name.
    #[must_use]
    pub fn name(&self) -> &str {
        &self.name
    }

    /// Returns direct nested subcommand branches.
    #[must_use]
    pub fn children(&self) -> &[CommandBranch] {
        &self.children
    }

    /// Returns this branch's argument schema, if it accepts arguments.
    #[must_use]
    pub fn schema_ref(&self) -> Option<&CommandSchema> {
        self.schema.as_ref()
    }

    /// Resolves this branch description for the requested locale.
    #[must_use]
    pub fn localized_description(&self, locale: Option<&str>) -> &str {
        self.description.resolve(locale)
    }

    /// Returns alternative branch names accepted by the parser.
    #[must_use]
    pub fn aliases_list(&self) -> &[Arc<str>] {
        &self.aliases
    }

    /// Returns this branch's interactive recovery configuration, if set.
    #[must_use]
    pub fn completion_ref(&self) -> Option<&CompletionConfig> {
        self.completion.as_ref()
    }

    /// Returns whether this branch is hidden from discovery surfaces.
    #[must_use]
    pub const fn is_hidden(&self) -> bool {
        self.hidden
    }

    pub(in crate::command) fn native_option(&self) -> CommandOption {
        let kind = if self.children.is_empty() {
            CommandOptionType::Subcommand
        } else {
            CommandOptionType::SubcommandGroup
        };
        let mut options = self
            .schema
            .as_ref()
            .map_or_else(Vec::new, CommandSchema::native_options);
        options.extend(self.children.iter().map(CommandBranch::native_option));
        CommandOption {
            id: Some(format!("oxidebot-node:{}", self.id.0)),
            name: Localized::new(self.name.replace('_', "-")),
            description: if self.description.is_empty() {
                Localized::new(self.name.to_string())
            } else {
                self.description.to_core()
            },
            kind,
            required: false,
            choices: Vec::new(),
            options,
            autocomplete: false,
            min_value: None,
            max_value: None,
            min_length: None,
            max_length: None,
            allowed_conversation_kinds: Vec::new(),
            platform_data: None,
        }
    }

    pub(in crate::command) fn rebase(&mut self, path: &str) {
        self.id = CommandNodeId(stable_hash(path.as_bytes()) as u32);
        if let Some(schema) = &mut self.schema {
            schema.rebase(path);
        }
        for child in &mut self.children {
            child.rebase(&format!("{path}.{}", child.name));
        }
    }

    pub(in crate::command) fn matches(&self, value: &str, case_sensitive: bool) -> bool {
        same_word(value, &self.name, case_sensitive)
            || self
                .aliases
                .iter()
                .any(|alias| same_word(value, alias, case_sensitive))
    }

    pub(in crate::command) fn validate(&self, path: &str) -> Result<(), String> {
        if self.name.trim().is_empty()
            || self.name.trim() != self.name.as_ref()
            || self.name.chars().any(char::is_whitespace)
        {
            return Err(format!("invalid subcommand name `{path}`"));
        }
        let mut names = HashSet::new();
        for name in std::iter::once(&self.name).chain(self.aliases.iter()) {
            if name.trim().is_empty()
                || name.trim() != name.as_ref()
                || name.chars().any(char::is_whitespace)
            {
                return Err(format!(
                    "invalid subcommand name or alias `{name}` in `{path}`"
                ));
            }
            if !names.insert(name.to_ascii_lowercase()) {
                return Err(format!("duplicate subcommand alias in `{path}`"));
            }
        }
        if let Some(schema) = &self.schema {
            schema.validate()?;
        }
        if self.schema.is_some() && !self.children.is_empty() {
            return Err(format!(
                "subcommand `{path}` cannot contain both arguments and nested subcommands"
            ));
        }
        if let Some(completion) = &self.completion {
            if completion.timeout.is_zero()
                || completion.max_rounds == 0
                || completion.max_attempts_per_field == 0
            {
                return Err(format!(
                    "subcommand `{path}` has an invalid completion policy"
                ));
            }
        }
        let mut child_names = HashSet::new();
        for child in &self.children {
            for name in std::iter::once(&child.name).chain(child.aliases.iter()) {
                if !child_names.insert(name.to_ascii_lowercase()) {
                    return Err(format!(
                        "subcommand `{path}` contains duplicate child name or alias `{name}`"
                    ));
                }
            }
            child.validate(&format!("{path} {}", child.name))?;
        }
        Ok(())
    }
}
