//! Command argument schemas and option specifications.
//!
//! This module owns declarative argument metadata, schema composition,
//! validation, native command option conversion, and stable field IDs.

use super::*;

#[path = "command_argument.rs"]
mod argument;

pub use argument::ArgumentSpec;

/// Runtime-neutral schema generated by `#[derive(CommandArgs)]` or built by
/// hand. The same schema drives text parsing, native commands, help, completion,
/// validation, and interactive recovery.
#[derive(Clone, Debug, Default)]
pub struct CommandSchema {
    pub(super) arguments: Vec<ArgumentSpec>,
    pub(super) groups: Vec<ArgumentGroup>,
}

impl CommandSchema {
    /// Creates an empty schema.
    #[must_use]
    pub fn new() -> Self {
        Self::default()
    }

    /// Adds one positional argument or named option.
    #[must_use]
    pub fn argument(mut self, argument: ArgumentSpec) -> Self {
        self.arguments.push(argument);
        self
    }

    /// Adds a cross-field argument group constraint.
    #[must_use]
    pub fn group(mut self, group: ArgumentGroup) -> Self {
        self.groups.push(group);
        self
    }

    /// Returns arguments in declaration order.
    #[must_use]
    pub fn arguments(&self) -> &[ArgumentSpec] {
        &self.arguments
    }

    /// Returns group constraints in declaration order.
    #[must_use]
    pub fn groups(&self) -> &[ArgumentGroup] {
        &self.groups
    }

    /// Finds an argument by its schema name.
    #[must_use]
    pub fn find(&self, name: &str) -> Option<&ArgumentSpec> {
        self.arguments
            .iter()
            .find(|argument| argument.name.as_ref() == name)
    }

    /// Finds an argument by its stable schema-local ID.
    #[must_use]
    pub fn find_by_id(&self, id: CommandFieldId) -> Option<&ArgumentSpec> {
        self.arguments.iter().find(|argument| argument.id == id)
    }

    /// Returns a schema that appends `other` after this schema.
    #[must_use]
    pub fn merged(&self, other: &Self) -> Self {
        let mut arguments =
            Vec::with_capacity(self.arguments.len().saturating_add(other.arguments.len()));
        arguments.extend(self.arguments.iter().cloned());
        arguments.extend(other.arguments.iter().cloned());
        let mut groups = Vec::with_capacity(self.groups.len().saturating_add(other.groups.len()));
        groups.extend(self.groups.iter().cloned());
        groups.extend(other.groups.iter().cloned());
        Self { arguments, groups }
    }

    pub(super) fn rebase(&mut self, path: &str) {
        for argument in &mut self.arguments {
            argument.rebase(path);
        }
    }

    /// Converts arguments into portable native command options.
    #[must_use]
    pub fn native_options(&self) -> Vec<CommandOption> {
        self.arguments
            .iter()
            .filter(|argument| !argument.is_hidden())
            .map(ArgumentSpec::native_option)
            .collect()
    }

    pub(crate) fn validate(&self) -> Result<(), String> {
        let mut ids = HashSet::new();
        let mut names = HashSet::new();
        let mut longs = HashSet::new();
        let mut shorts = HashSet::new();
        let mut seen_optional_positional = false;
        let mut seen_variadic = false;
        for argument in &self.arguments {
            if !ids.insert(argument.id) {
                return Err(format!(
                    "command schema contains colliding field id {:?} for `{}`",
                    argument.id, argument.name
                ));
            }
            if argument.name.trim().is_empty()
                || argument.name.trim() != argument.name.as_ref()
                || argument.name.chars().any(char::is_whitespace)
                || !names.insert(argument.name.clone())
            {
                return Err(format!("duplicate or invalid argument `{}`", argument.name));
            }
            if argument.long.as_deref().is_some_and(|name| {
                name.is_empty()
                    || name.starts_with('-')
                    || name.contains('=')
                    || name.chars().any(char::is_whitespace)
            }) {
                return Err(format!("invalid long option for `{}`", argument.name));
            }
            if argument
                .short
                .is_some_and(|name| name == '-' || name.is_whitespace() || name.is_ascii_digit())
            {
                return Err(format!("invalid short option for `{}`", argument.name));
            }
            if argument.flag && argument.multiple && argument.action != ArgumentAction::Count {
                return Err(format!(
                    "flag `{}` cannot be multiple unless it uses the count action",
                    argument.name
                ));
            }
            if argument.flag && argument.default.is_some() {
                return Err(format!(
                    "flag `{}` cannot have a default value",
                    argument.name
                ));
            }
            if argument.flag && argument.required {
                return Err(format!("flag `{}` cannot be required", argument.name));
            }
            if argument.default.is_some() && argument.required {
                return Err(format!(
                    "defaulted argument `{}` cannot also be required",
                    argument.name
                ));
            }
            if argument.default.is_some() && (argument.multiple || argument.rest) {
                return Err(format!(
                    "variadic argument `{}` cannot have a default value",
                    argument.name
                ));
            }
            if argument.flag && argument.is_positional() {
                return Err(format!(
                    "flag `{}` needs a long or short option name",
                    argument.name
                ));
            }
            if matches!(
                argument.action,
                ArgumentAction::SetTrue | ArgumentAction::SetFalse | ArgumentAction::Count
            ) && argument.is_positional()
            {
                return Err(format!(
                    "action {:?} on `{}` requires a long or short option",
                    argument.action, argument.name
                ));
            }
            if argument.action == ArgumentAction::Append && !argument.is_multiple() {
                return Err(format!(
                    "append action on `{}` requires multiple values",
                    argument.name
                ));
            }
            if argument
                .long
                .as_ref()
                .is_some_and(|name| !longs.insert(name.clone()))
            {
                return Err(format!("duplicate long option for `{}`", argument.name));
            }
            if argument.short.is_some_and(|name| !shorts.insert(name)) {
                return Err(format!("duplicate short option for `{}`", argument.name));
            }
            if argument.rest && !argument.is_positional() {
                return Err(format!(
                    "rest argument `{}` must be positional",
                    argument.name
                ));
            }
            if argument.rest || (argument.multiple && argument.is_positional()) {
                if seen_variadic {
                    return Err("a command can have only one variadic positional argument".into());
                }
                seen_variadic = true;
            } else if seen_variadic && argument.is_positional() {
                return Err("variadic argument must be the final positional argument".into());
            }
            if argument.is_positional() {
                if !argument.required || argument.default.is_some() {
                    seen_optional_positional = true;
                } else if seen_optional_positional && !argument.rest {
                    return Err("required positional argument follows an optional one".into());
                }
            }
            if argument
                .min_value
                .zip(argument.max_value)
                .is_some_and(|(min, max)| min > max)
            {
                return Err(format!("invalid numeric range for `{}`", argument.name));
            }
            if argument
                .min_length
                .zip(argument.max_length)
                .is_some_and(|(min, max)| min > max)
            {
                return Err(format!("invalid length range for `{}`", argument.name));
            }
            let mut choice_values = HashSet::new();
            if argument
                .choices
                .iter()
                .any(|choice| !choice_values.insert(choice.value.clone()))
            {
                return Err(format!("duplicate choice for `{}`", argument.name));
            }
        }

        for argument in &self.arguments {
            for required in &argument.requires {
                if required == &argument.name || !names.contains(required) {
                    return Err(format!(
                        "argument `{}` requires unknown or self field `{required}`",
                        argument.name
                    ));
                }
            }
            for conflict in &argument.conflicts {
                if conflict == &argument.name || !names.contains(conflict) {
                    return Err(format!(
                        "argument `{}` conflicts with unknown or self field `{conflict}`",
                        argument.name
                    ));
                }
            }
        }
        let mut group_names = HashSet::new();
        for group in &self.groups {
            if group.name.trim().is_empty()
                || group.name.trim() != group.name.as_ref()
                || group.name.chars().any(char::is_whitespace)
                || !group_names.insert(Arc::clone(&group.name))
            {
                return Err(format!(
                    "duplicate or invalid argument group `{}`",
                    group.name
                ));
            }
            if group.arguments.is_empty() {
                return Err(format!("argument group `{}` has no members", group.name));
            }
            let mut members = HashSet::new();
            for member in &group.arguments {
                if !names.contains(member) || !members.insert(Arc::clone(member)) {
                    return Err(format!(
                        "argument group `{}` references unknown or duplicate field `{member}`",
                        group.name
                    ));
                }
            }
        }
        Ok(())
    }
}
