use crate::{
    handler::EventContext, router::reply_target, Bot, CommandMatch, CommandParseError, Context,
    Dialogue, FromCommandMatch, HandlerError, Messenger, Outcome, Reply, ShutdownSignal,
};
use oxidebot_core::{
    conversation::{ConversationRef, MessageTarget},
    event::{EventTag, LifecycleEvent, RequestEvent},
    source::{message::MessageSegment, user::User},
    BotIdentity, Event, EventId,
};
use std::{fmt, ops::Deref, sync::Arc};

/// A safe, user-facing error produced while extracting a handler argument.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ExtractError {
    message: Arc<str>,
}

impl ExtractError {
    /// Creates a user-facing extraction failure.
    #[must_use]
    pub fn new(message: impl Into<Arc<str>>) -> Self {
        Self {
            message: message.into(),
        }
    }

    /// Returns the user-facing extraction message.
    #[must_use]
    pub fn message(&self) -> &str {
        &self.message
    }

    pub(crate) fn into_outcome(self) -> Outcome {
        Outcome::new().text(self.message.to_string())
    }
}

impl fmt::Display for ExtractError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.message)
    }
}

impl std::error::Error for ExtractError {}

impl From<ExtractError> for HandlerError {
    fn from(error: ExtractError) -> Self {
        Self::user(error.message)
    }
}

/// Extracts one typed value from the common event [`Context`].
///
/// Extraction is synchronous and monomorphized. Interactive command completion
/// is performed once by the command handler before argument extraction, so
/// ordinary message and event handlers do not allocate boxed extractor futures.
pub trait Extract<S>: Sized
where
    S: Send + Sync + 'static,
{
    /// Extracts this typed value from a handler context.
    fn extract(context: &Context<S>) -> Result<Self, ExtractError>;
}

/// Extracted raw text of a message event.
#[derive(Clone, Debug)]
pub struct Text(pub String);

impl Deref for Text {
    type Target = str;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

/// Extracted normalized segments of a message event.
#[derive(Clone, Debug)]
pub struct Segments(pub Vec<MessageSegment>);

impl Deref for Segments {
    type Target = [MessageSegment];

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

/// Extracted sender of a message or interaction event.
#[derive(Clone, Debug)]
pub struct Sender(pub User);

impl Deref for Sender {
    type Target = User;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

/// Extracted required conversation reference.
#[derive(Clone, Debug)]
pub struct Conversation(pub ConversationRef);

impl Deref for Conversation {
    type Target = ConversationRef;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

/// Extracted optional conversation reference.
#[derive(Clone, Debug)]
pub struct MaybeConversation(pub Option<ConversationRef>);

impl Deref for MaybeConversation {
    type Target = Option<ConversationRef>;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

/// Extracted identifier of the current inbound platform message.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct IncomingMessageId(pub oxidebot_core::MessageId);

impl Deref for IncomingMessageId {
    type Target = oxidebot_core::MessageId;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

/// Extracted target used for a reply or outbound message.
#[derive(Clone, Debug)]
pub struct Target(pub MessageTarget);

impl Deref for Target {
    type Target = MessageTarget;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

/// Compile-time conversion from an application root state to one focused
/// service. Implementations are normally generated by `#[derive(BotState)]`.
///
/// This is a static trait, not a runtime type map: extraction is monomorphized
/// and only clones the selected service (or its `Arc`).
pub trait FromState<Root>: Send + Sync + Sized + 'static
where
    Root: Send + Sync + 'static,
{
    /// Selects this focused service from shared application root state.
    fn from_state(root: &Arc<Root>) -> Arc<Self>;
}

impl<T> FromState<T> for T
where
    T: Send + Sync + 'static,
{
    fn from_state(root: &Arc<T>) -> Arc<Self> {
        Arc::clone(root)
    }
}

/// The application root state or one statically selected service.
#[derive(Debug)]
pub struct State<S>(pub Arc<S>);

impl<S> Clone for State<S> {
    fn clone(&self) -> Self {
        Self(Arc::clone(&self.0))
    }
}

impl<S> Deref for State<S> {
    type Target = S;

    fn deref(&self) -> &Self::Target {
        self.0.as_ref()
    }
}

/// Strongly typed command arguments.
#[derive(Clone, Debug)]
pub struct Args<T>(pub T);

impl<T> Deref for Args<T> {
    type Target = T;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl<S> Extract<S> for Context<S>
where
    S: Send + Sync + 'static,
{
    fn extract(context: &Context<S>) -> Result<Self, ExtractError> {
        Ok(context.clone())
    }
}

impl<S> Extract<S> for Text
where
    S: Send + Sync + 'static,
{
    fn extract(context: &Context<S>) -> Result<Self, ExtractError> {
        context
            .message()
            .map(|event| Self(event.message.get_raw_text()))
            .ok_or_else(|| ExtractError::new("this handler requires a message event"))
    }
}

impl<S> Extract<S> for Segments
where
    S: Send + Sync + 'static,
{
    fn extract(context: &Context<S>) -> Result<Self, ExtractError> {
        context
            .message()
            .map(|event| Self(event.message.segments.clone()))
            .ok_or_else(|| ExtractError::new("this handler requires a message event"))
    }
}

impl<S> Extract<S> for Sender
where
    S: Send + Sync + 'static,
{
    fn extract(context: &Context<S>) -> Result<Self, ExtractError> {
        sender_for_event(context.event())
            .cloned()
            .map(Self)
            .ok_or_else(|| ExtractError::new("this event has no sender"))
    }
}

impl<S> Extract<S> for Conversation
where
    S: Send + Sync + 'static,
{
    fn extract(context: &Context<S>) -> Result<Self, ExtractError> {
        conversation_for_event(context.event())
            .cloned()
            .map(Self)
            .ok_or_else(|| ExtractError::new("this event has no conversation"))
    }
}

impl<S> Extract<S> for MaybeConversation
where
    S: Send + Sync + 'static,
{
    fn extract(context: &Context<S>) -> Result<Self, ExtractError> {
        Ok(Self(conversation_for_event(context.event()).cloned()))
    }
}

impl<S> Extract<S> for IncomingMessageId
where
    S: Send + Sync + 'static,
{
    fn extract(context: &Context<S>) -> Result<Self, ExtractError> {
        context
            .message()
            .and_then(|event| event.message.id.clone().map(Self))
            .ok_or_else(|| ExtractError::new("this event has no message id"))
    }
}

impl<S> Extract<S> for Target
where
    S: Send + Sync + 'static,
{
    fn extract(context: &Context<S>) -> Result<Self, ExtractError> {
        reply_target(context.event())
            .map(Self)
            .ok_or_else(|| ExtractError::new("this event has no natural reply target"))
    }
}

impl<Root, Selected> Extract<Root> for State<Selected>
where
    Root: Send + Sync + 'static,
    Selected: FromState<Root>,
{
    fn extract(context: &Context<Root>) -> Result<Self, ExtractError> {
        Ok(Self(Selected::from_state(&context.state)))
    }
}

impl<S> Extract<S> for Bot
where
    S: Send + Sync + 'static,
{
    fn extract(context: &Context<S>) -> Result<Self, ExtractError> {
        context
            .bot()
            .map(Self)
            .map_err(|_| ExtractError::new("the current adapter does not expose the OxideBot API"))
    }
}

impl<S> Extract<S> for Reply
where
    S: Send + Sync + 'static,
{
    fn extract(context: &Context<S>) -> Result<Self, ExtractError> {
        context.bot().map_err(|_| {
            ExtractError::new("the current adapter does not expose the OxideBot API")
        })?;
        let target = reply_target(context.event())
            .ok_or_else(|| ExtractError::new("this event has no natural reply target"))?;
        let reply_to = context.message().and_then(|event| event.message.id.clone());
        let pipeline: Arc<dyn crate::authoring::ErasedDeliveryPipeline> =
            Arc::new(crate::authoring::BoundDeliveryPipeline {
                runtime: context.authoring_arc(),
                context: context.clone(),
            });
        Ok(Self::new(
            context.bot.clone(),
            target,
            reply_to,
            Some(pipeline),
        ))
    }
}

impl<S> Extract<S> for Messenger
where
    S: Send + Sync + 'static,
{
    fn extract(context: &Context<S>) -> Result<Self, ExtractError> {
        Ok(Self::new(
            Reply::extract(context)?,
            context.bot_identity().clone(),
            context.authoring().bots(),
        ))
    }
}

impl<S> Extract<S> for crate::Responder
where
    S: Send + Sync + 'static,
{
    fn extract(context: &Context<S>) -> Result<Self, ExtractError> {
        context.responder().cloned().ok_or_else(|| {
            ExtractError::new("this handler requires an answerable interaction event")
        })
    }
}

impl<S> Extract<S> for Dialogue
where
    S: Send + Sync + 'static,
{
    fn extract(context: &Context<S>) -> Result<Self, ExtractError> {
        dialogue_from_context(context)
    }
}

impl<S> Extract<S> for CommandMatch
where
    S: Send + Sync + 'static,
{
    fn extract(context: &Context<S>) -> Result<Self, ExtractError> {
        context
            .command()
            .cloned()
            .ok_or_else(|| ExtractError::new("this handler requires a command"))
    }
}

impl<S, T> Extract<S> for Args<T>
where
    S: Send + Sync + 'static,
    T: FromCommandMatch,
{
    fn extract(context: &Context<S>) -> Result<Self, ExtractError> {
        let result = context
            .command()
            .cloned()
            .ok_or_else(|| ExtractError::new("this handler requires a command"))?;
        T::from_match(&result)
            .map(Self)
            .map_err(|error| command_extract_error(&result, error))
    }
}

impl<S, T> Extract<S> for EventContext<T>
where
    S: Send + Sync + 'static,
    T: EventTag,
{
    fn extract(context: &Context<S>) -> Result<Self, ExtractError> {
        EventContext::from_context(context).ok_or_else(|| {
            ExtractError::new(format!("this handler requires event type {:?}", T::TYPE))
        })
    }
}

impl<S> Extract<S> for BotIdentity
where
    S: Send + Sync + 'static,
{
    fn extract(context: &Context<S>) -> Result<Self, ExtractError> {
        Ok(context.bot_identity().clone())
    }
}

impl<S> Extract<S> for EventId
where
    S: Send + Sync + 'static,
{
    fn extract(context: &Context<S>) -> Result<Self, ExtractError> {
        Ok(context.envelope.id.clone())
    }
}

impl<S> Extract<S> for ShutdownSignal
where
    S: Send + Sync + 'static,
{
    fn extract(context: &Context<S>) -> Result<Self, ExtractError> {
        Ok(context.shutdown.clone())
    }
}

fn command_extract_error(result: &CommandMatch, error: CommandParseError) -> ExtractError {
    ExtractError::new(format!("{error}\n\n用法：{}", result.command().usage()))
}

fn dialogue_from_context<S>(context: &Context<S>) -> Result<Dialogue, ExtractError>
where
    S: Send + Sync + 'static,
{
    let conversation = context
        .envelope
        .index
        .conversation
        .clone()
        .ok_or_else(|| ExtractError::new("this event has no conversation scope"))?;
    let actor = context
        .envelope
        .index
        .actor
        .clone()
        .ok_or_else(|| ExtractError::new("this event has no actor scope"))?;
    let target = reply_target(context.event())
        .ok_or_else(|| ExtractError::new("this event has no natural reply target"))?;
    context
        .bot()
        .map_err(|_| ExtractError::new("the current adapter does not expose the OxideBot API"))?;
    Ok(Dialogue::new(
        context.bot.clone(),
        context.sessions.clone(),
        conversation,
        actor,
        target,
        Some(Arc::new(crate::authoring::BoundDeliveryPipeline {
            runtime: context.authoring_arc(),
            context: context.clone(),
        })),
    ))
}

fn sender_for_event(event: &Event) -> Option<&User> {
    match event {
        Event::Message(event) => Some(&event.sender),
        Event::Lifecycle(event) => match event {
            LifecycleEvent::GroupMemberJoined(event) => Some(&event.user),
            LifecycleEvent::GroupMemberLeft(event) => Some(&event.user),
            LifecycleEvent::GroupAdminChanged(event) => Some(&event.user),
            LifecycleEvent::GroupMuteChanged(event) => event.operator.as_ref(),
            LifecycleEvent::GroupMemberMuteChanged(event) => Some(&event.user),
            LifecycleEvent::GroupHighlightChanged(event) => {
                event.sender.as_ref().or(event.operator.as_ref())
            }
            LifecycleEvent::GroupMemberAliasChanged(event) => Some(&event.user),
            LifecycleEvent::MessageReactionsChanged(event) => Some(&event.user),
            LifecycleEvent::MessageDeleted(event) => {
                event.user.as_ref().or(event.operator.as_ref())
            }
            LifecycleEvent::MessageEdited(event) => Some(&event.user),
            _ => None,
        },
        Event::Request(event) => match event {
            RequestEvent::Friend(event) => Some(&event.user),
            RequestEvent::GroupJoin(event) => Some(&event.user),
            RequestEvent::GroupInvite(event) => Some(&event.user),
        },
        Event::Interaction(event) => Some(&event.user),
        Event::Meta(_) | Event::Native(_) => None,
    }
}

fn conversation_for_event(event: &Event) -> Option<&ConversationRef> {
    match event {
        Event::Message(event) => Some(&event.conversation),
        Event::Lifecycle(event) => match event {
            LifecycleEvent::GroupMemberJoined(event) => Some(&event.conversation),
            LifecycleEvent::GroupMemberLeft(event) => Some(&event.conversation),
            LifecycleEvent::GroupAdminChanged(event) => Some(&event.conversation),
            LifecycleEvent::GroupMuteChanged(event) => Some(&event.conversation),
            LifecycleEvent::GroupMemberMuteChanged(event) => Some(&event.conversation),
            LifecycleEvent::GroupHighlightChanged(event) => Some(&event.conversation),
            LifecycleEvent::GroupMemberAliasChanged(event) => Some(&event.conversation),
            LifecycleEvent::MessageReactionsChanged(event) => event.conversation.as_ref(),
            LifecycleEvent::MessageDeleted(event) => event.conversation.as_ref(),
            LifecycleEvent::MessageEdited(event) => event.conversation.as_ref(),
            _ => None,
        },
        Event::Request(RequestEvent::GroupJoin(event)) => Some(&event.conversation),
        Event::Request(RequestEvent::GroupInvite(event)) => Some(&event.conversation),
        Event::Interaction(event) => event.conversation.as_ref(),
        Event::Request(RequestEvent::Friend(_)) | Event::Meta(_) | Event::Native(_) => None,
    }
}
