//! Flat module composition, registration, and handler assembly.

use super::*;

impl Command {
    /// Binds this command and an ordinary async function into one locally
    /// configurable feature.
    #[must_use]
    pub fn handle<S, H, T>(self, handler: H) -> Feature<S>
    where
        S: Send + Sync + 'static,
        H: IntoHandler<T, S>,
    {
        Feature::command(self, handler)
    }
}

impl<S> Default for Module<S>
where
    S: Send + Sync + 'static,
{
    fn default() -> Self {
        Self::new()
    }
}

impl<S> Module<S>
where
    S: Send + Sync + 'static,
{
    /// Creates an empty flat module.
    #[must_use]
    pub fn new() -> Self {
        Self {
            handlers: Vec::new(),
            guards: Vec::new(),
            before: Vec::new(),
            after: Vec::new(),
            default_scope: RouteScope::global(),
            scope_errors: Vec::new(),
            has_help: false,
            runtime_shortcuts: false,
            overlays: Vec::new(),
            completers: HashMap::new(),
        }
    }

    /// Installs one generated or manually configured Bot feature.
    #[must_use]
    #[allow(
        clippy::should_implement_trait,
        reason = "`add` installs a feature into this fluent module builder; it is not arithmetic"
    )]
    pub fn add<F>(self, feature: F) -> Self
    where
        F: crate::IntoFeature<S>,
    {
        feature.install(self)
    }

    /// Handles one exact public event type.
    #[must_use]
    pub fn on<E, H, T>(self, event: E, handler: H) -> Self
    where
        E: EventTag,
        H: IntoHandler<T, S>,
    {
        self.add(Feature::event(event, handler))
    }

    /// Handles every ordinary message event.
    #[must_use]
    pub fn message<H, T>(self, handler: H) -> Self
    where
        H: IntoHandler<T, S>,
    {
        self.add(Feature::message(handler))
    }

    /// Handles one strongly typed command.
    #[must_use]
    pub fn command<H, T>(self, command: Command, handler: H) -> Self
    where
        H: IntoHandler<T, S>,
    {
        self.add(Feature::command(command, handler))
    }

    /// Handles a complete command grammar generated by `#[derive(BotCommand)]`.
    #[must_use]
    pub fn command_tree<C, H, T>(self, handler: H) -> Self
    where
        C: crate::command::CommandTree,
        H: IntoHandler<T, S>,
    {
        self.add(Feature::command_tree::<C, H, T>(handler))
    }

    /// Registers a handler for one statically generated branch of a command tree.
    #[must_use]
    pub fn command_branch<B, H, T>(self, branch: B, handler: H) -> Self
    where
        B: crate::CommandBranchTag,
        H: IntoHandler<T, S>,
    {
        self.add(Feature::command_branch(branch, handler))
    }

    /// Handles one interaction custom identifier.
    #[must_use]
    pub fn interaction<H, T>(self, custom_id: impl Into<Arc<str>>, handler: H) -> Self
    where
        H: IntoHandler<T, S>,
    {
        self.add(Feature::interaction(custom_id, handler))
    }

    /// Handles one platform-native lifecycle identifier.
    #[must_use]
    pub fn native<H, T>(self, kind: impl Into<Arc<str>>, handler: H) -> Self
    where
        H: IntoHandler<T, S>,
    {
        self.add(Feature::native(kind, handler))
    }

    /// Includes another feature module in registration order.
    ///
    /// No command prefix, route tree, runtime, or event bus is introduced.
    #[must_use]
    pub fn include(mut self, mut other: Self) -> Self {
        other.bake_hooks();
        self.scope_errors.append(&mut other.scope_errors);
        if !self.default_scope.is_global() {
            for handler in &mut other.handlers {
                match handler.scope.intersect(&self.default_scope) {
                    Ok(scope) => handler.scope = scope,
                    Err(error) => self.scope_errors.push(error),
                }
            }
        }
        if self.has_help && other.has_help {
            let existing_help_scopes = self
                .handlers
                .iter()
                .filter(|handler| matches!(&handler.endpoint, EndpointKind::Help))
                .map(|handler| handler.scope.clone())
                .collect::<Vec<_>>();
            other.handlers.retain(|handler| {
                !matches!(&handler.endpoint, EndpointKind::Help)
                    || !existing_help_scopes
                        .iter()
                        .any(|scope| scope.overlaps(&handler.scope))
            });
        }
        self.has_help |= other.has_help;
        self.runtime_shortcuts |= other.runtime_shortcuts;
        self.overlays.append(&mut other.overlays);
        for (key, provider) in other.completers.drain() {
            if self.completers.insert(key, provider).is_some() {
                self.scope_errors.push(format!(
                    "more than one dynamic completer is registered for command {:016x}, field {:08x}",
                    key.0.0,
                    key.1.0,
                ));
            }
        }
        self.handlers.append(&mut other.handlers);
        self
    }

    /// Enables the bounded runtime shortcut registry for this application.
    /// Added shortcuts select only their owning command IDs before parsing;
    /// they do not move unrelated commands onto the broad message path.
    #[must_use]
    pub const fn runtime_shortcuts(mut self) -> Self {
        self.runtime_shortcuts = true;
        self
    }

    pub(crate) const fn runtime_shortcuts_enabled(&self) -> bool {
        self.runtime_shortcuts
    }

    /// Applies a data-only metadata overlay to matching commands regardless of
    /// whether the overlay is declared before or after included modules.
    #[must_use]
    pub fn command_overlay(mut self, overlay: crate::CommandOverlay) -> Self {
        self.overlays.push(overlay);
        self
    }

    /// Applies an async admission rule to every handler in this module,
    /// including handlers from included modules.
    #[must_use]
    pub fn guard<G>(mut self, guard: G) -> Self
    where
        G: Guard<S>,
    {
        self.guards.push(Arc::new(guard));
        self
    }

    /// Runs an async hook before each matched handler.
    #[must_use]
    pub fn before<B>(mut self, hook: B) -> Self
    where
        B: Before<S>,
    {
        self.before.push(Arc::new(hook));
        self
    }

    /// Runs an async hook after each matched handler.
    #[must_use]
    pub fn after<A>(mut self, hook: A) -> Self
    where
        A: After<S>,
    {
        self.after.push(Arc::new(hook));
        self
    }

    /// Restricts every handler in this module to one platform, regardless of declaration order.
    #[must_use]
    pub fn for_platform(mut self, platform: PlatformId) -> Self {
        let restriction = RouteScope::for_platform(platform);
        self.restrict_scope(&restriction);
        self
    }

    /// Restricts every handler in this module to one bot, regardless of declaration order.
    #[must_use]
    pub fn for_bot(mut self, bot: BotIdentity) -> Self {
        let restriction = RouteScope::for_bot(bot);
        self.restrict_scope(&restriction);
        self
    }

    /// Adds `/help [command]`, generated from the same schemas used for parsing.
    #[must_use]
    pub fn help(self) -> Self {
        self.help_command(
            crate::command("help")
                .alias("帮助")
                .description("显示命令目录或某个命令的详细帮助"),
        )
    }

    /// Adds a help handler using `command` as its command definition.
    #[must_use]
    pub fn help_command(mut self, command: Command) -> Self {
        if self.handlers.iter().any(|handler| {
            matches!(&handler.endpoint, EndpointKind::Help)
                && handler.scope.overlaps(&self.default_scope)
        }) {
            return self;
        }
        self.has_help = true;
        self.handlers.push(HandlerDefinition {
            selector: Selector::Command(command),
            endpoint: EndpointKind::Help,
            guards: Vec::new(),
            before: Vec::new(),
            after: Vec::new(),
            scope: self.default_scope.clone(),
            default_block: true,
            branch_filter: None,
        });
        self
    }

    /// Adds a conservative, opt-in suggestion for mistyped prefixed root
    /// commands.
    ///
    /// The helper never executes a suggested command. It only replies when a
    /// prefixed root name is within a small edit distance of one discoverable
    /// command. Because this is intentionally a broad message handler, enable
    /// it only where the small additional decode cost is desired.
    #[must_use]
    pub fn typo_assist(self) -> Self {
        let catalog = Arc::new(self.catalog());
        self.message(move |context: Context<S>| {
            let catalog = Arc::clone(&catalog);
            async move {
                let Event::Message(message) = context.event() else {
                    return Outcome::continue_();
                };
                let input = message.message.get_raw_text();
                let catalog = catalog
                    .for_identity(context.bot_identity())
                    .enabled(&context.authoring().registry);
                let Some(suggestion) = catalog.suggest_root_command(&input) else {
                    return Outcome::continue_();
                };
                let locale = context.authoring().locale(&context).await;
                let text = if locale
                    .as_deref()
                    .is_some_and(|locale| !locale.starts_with("zh"))
                {
                    format!("Unknown command. Did you mean `{suggestion}`?")
                } else {
                    format!("未知命令；你是不是想输入 `{suggestion}`？")
                };
                Outcome::stop().text(text)
            }
        })
    }

    /// Returns the scoped command catalog after applying metadata overlays.
    #[must_use]
    pub fn catalog(&self) -> CommandCatalog {
        let mut seen = std::collections::HashSet::new();
        CommandCatalog::scoped(self.handlers.iter().filter_map(|handler| {
            if let Selector::Command(command) = &handler.selector {
                let command = self.apply_overlays_to(command.clone());
                let key = (command.id(), handler.scope.clone());
                if seen.insert(key) {
                    Some((command, handler.scope.clone()))
                } else {
                    None
                }
            } else {
                None
            }
        }))
    }

    pub(crate) fn install_completers(
        &self,
        target: &mut HashMap<(CommandId, CommandFieldId), Arc<dyn DynamicCompleter<S>>>,
    ) -> Result<(), BuildError> {
        for (key, provider) in &self.completers {
            if target.insert(*key, Arc::clone(provider)).is_some() {
                return Err(BuildError::InvalidRoute(format!(
                    "more than one dynamic completer is registered for command {:016x}, field {:08x}",
                    key.0.0,
                    key.1.0,
                )));
            }
        }
        Ok(())
    }

    fn apply_overlays_to(&self, mut command: Command) -> Command {
        for overlay in &self.overlays {
            if overlay.matches(&command) {
                command = overlay.apply(command);
            }
        }
        command
    }

    fn apply_overlays(&mut self) {
        let overlays = self.overlays.clone();
        for handler in &mut self.handlers {
            let Selector::Command(command) = &mut handler.selector else {
                continue;
            };
            for overlay in &overlays {
                if overlay.matches(command) {
                    *command = overlay.apply(command.clone());
                }
            }
        }
    }

    pub(crate) fn into_handlers(mut self) -> Result<Vec<Arc<dyn ErasedHandler<S>>>, BuildError> {
        self.apply_overlays();
        self.overlays.clear();
        if let Some(error) = self.scope_errors.first().cloned() {
            return Err(BuildError::InvalidRoute(error));
        }
        validate_command_conflicts(&self.handlers).map_err(BuildError::InvalidRoute)?;
        self.bake_hooks();
        let catalog = Arc::new(self.catalog());
        let mut output: Vec<Arc<dyn ErasedHandler<S>>> = Vec::new();

        for definition in self.handlers {
            let endpoint: Arc<dyn Endpoint<S>> = match definition.endpoint {
                EndpointKind::Handler(endpoint) => endpoint,
                EndpointKind::Help => Arc::new(HelpEndpoint::<S> {
                    catalog: Arc::clone(&catalog),
                    _state: PhantomData,
                }),
            };
            match definition.selector {
                Selector::Event { event_type, kind } => {
                    output.push(Arc::new(ModuleHandler {
                        spec: RouteSpec::Event(event_type),
                        event_kind: kind,
                        scope: definition.scope,
                        endpoint,
                        guards: definition.guards.into(),
                        before: definition.before.into(),
                        after: definition.after.into(),
                        command: None,
                        default_block: definition.default_block,
                        branch_filter: definition.branch_filter.clone(),
                    }));
                }
                Selector::Interaction(custom_id) => {
                    output.push(Arc::new(ModuleHandler {
                        spec: RouteSpec::Interaction(custom_id),
                        event_kind: DispatchKind::Interaction,
                        scope: definition.scope,
                        endpoint,
                        guards: definition.guards.into(),
                        before: definition.before.into(),
                        after: definition.after.into(),
                        command: None,
                        default_block: definition.default_block,
                        branch_filter: definition.branch_filter.clone(),
                    }));
                }
                Selector::Native(kind) => {
                    output.push(Arc::new(ModuleHandler {
                        spec: RouteSpec::Native(kind),
                        event_kind: DispatchKind::Native,
                        scope: definition.scope,
                        endpoint,
                        guards: definition.guards.into(),
                        before: definition.before.into(),
                        after: definition.after.into(),
                        command: None,
                        default_block: definition.default_block,
                        branch_filter: definition.branch_filter.clone(),
                    }));
                }
                Selector::Command(command) => {
                    command.validate().map_err(BuildError::InvalidRoute)?;
                    let specs = command.fast_route_keys().map_or_else(
                        || vec![RouteSpec::Event(EventType::Message)],
                        |keys| keys.into_iter().map(RouteSpec::Command).collect(),
                    );
                    for spec in specs {
                        output.push(Arc::new(ModuleHandler {
                            spec,
                            event_kind: DispatchKind::Message,
                            scope: definition.scope.clone(),
                            endpoint: Arc::clone(&endpoint),
                            guards: definition.guards.clone().into(),
                            before: definition.before.clone().into(),
                            after: definition.after.clone().into(),
                            command: Some(command.clone()),
                            default_block: definition.default_block,
                            branch_filter: definition.branch_filter.clone(),
                        }));
                    }
                    output.push(Arc::new(ModuleHandler {
                        spec: RouteSpec::Event(EventType::Interaction),
                        event_kind: DispatchKind::Interaction,
                        scope: definition.scope,
                        endpoint,
                        guards: definition.guards.into(),
                        before: definition.before.into(),
                        after: definition.after.into(),
                        command: Some(command),
                        default_block: definition.default_block,
                        branch_filter: definition.branch_filter.clone(),
                    }));
                }
            }
        }
        if !catalog.commands().is_empty() {
            output.push(Arc::new(ModuleHandler {
                spec: RouteSpec::Event(EventType::LifecycleSuggestionRequested),
                event_kind: EventType::LifecycleSuggestionRequested.dispatch_kind(),
                scope: RouteScope::global(),
                endpoint: Arc::new(SuggestionEndpoint::<S> {
                    catalog,
                    _state: PhantomData,
                }),
                guards: Arc::from([]),
                before: Arc::from([]),
                after: Arc::from([]),
                command: None,
                default_block: true,
                branch_filter: None,
            }));
        }
        Ok(output)
    }

    fn restrict_scope(&mut self, restriction: &RouteScope) {
        for handler in &mut self.handlers {
            match handler.scope.intersect(restriction) {
                Ok(scope) => handler.scope = scope,
                Err(error) => self.scope_errors.push(error),
            }
        }
        match self.default_scope.intersect(restriction) {
            Ok(scope) => self.default_scope = scope,
            Err(error) => self.scope_errors.push(error),
        }
    }

    fn bake_hooks(&mut self) {
        if self.guards.is_empty() && self.before.is_empty() && self.after.is_empty() {
            return;
        }
        for handler in &mut self.handlers {
            if !self.guards.is_empty() {
                let mut guards = self.guards.clone();
                guards.append(&mut handler.guards);
                handler.guards = guards;
            }
            if !self.before.is_empty() {
                let mut before = self.before.clone();
                before.append(&mut handler.before);
                handler.before = before;
            }
            if !self.after.is_empty() {
                handler.after.extend(self.after.iter().cloned());
            }
        }
        self.guards.clear();
        self.before.clear();
        self.after.clear();
    }
}
