use crate::{
    command::tokenize_segments,
    function::IntoHandler,
    handler::{ErasedHandler, HandlerCall, RouteScope, RouteSpec},
    hooks::{
        After, Before, Endpoint, Guard, GuardDecision, SharedAfter, SharedBefore, SharedGuard,
    },
    BuildError, Command, CommandCatalog, CommandFieldId, CommandFieldTag, CommandId, CommandOutput,
    CommandParseError, CommandResult, CompletionConfig, CompletionInput, Context, Dialogue,
    DynamicCompleter, Extract, HandlerError, HandlerResult, Outcome, RewriteInput, Shortcut,
    SourceSpan,
};
use futures_util::future::BoxFuture;
use oxidebot_core::{
    event::{kernel::DispatchKind, tags, EventTag, EventType},
    interaction::InteractionKind,
    BotIdentity, Event, PlatformId,
};
use std::{collections::HashMap, marker::PhantomData, sync::Arc};

/// A flat, reusable Bot feature module.
///
/// A module groups commands, event handlers, guards, and lifecycle hooks. It is
/// deliberately not a URL tree: multi-word commands are declared as ordinary
/// command names, and including another module never creates hidden nesting.
pub struct Module<S = ()>
where
    S: Send + Sync + 'static,
{
    handlers: Vec<HandlerDefinition<S>>,
    guards: Vec<SharedGuard<S>>,
    before: Vec<SharedBefore<S>>,
    after: Vec<SharedAfter<S>>,
    default_scope: RouteScope,
    scope_errors: Vec<String>,
    has_help: bool,
    runtime_shortcuts: bool,
    overlays: Vec<crate::CommandOverlay>,
    completers: HashMap<(CommandId, CommandFieldId), Arc<dyn DynamicCompleter<S>>>,
}

/// One Bot feature with all of its local configuration kept together.
///
/// A feature represents one command, event, interaction, or native handler plus
/// its local guards, hooks, scope, propagation behavior, shortcuts, and dynamic
/// completion providers. It is not a nested router.
pub struct Feature<S = ()>
where
    S: Send + Sync + 'static,
{
    definition: HandlerDefinition<S>,
    completers: Vec<CompleterBinding<S>>,
    errors: Vec<String>,
    runtime_shortcuts: bool,
}

struct CompleterBinding<S>
where
    S: Send + Sync + 'static,
{
    command: crate::CommandId,
    field: crate::CommandFieldId,
    provider: Arc<dyn DynamicCompleter<S>>,
}

/// A generated or manually configured capability that can be installed into a
/// flat [`Module`].
pub trait IntoFeature<S>: Sized
where
    S: Send + Sync + 'static,
{
    fn install(self, module: Module<S>) -> Module<S>;
}

/// Implemented by values generated by `#[oxidebot::command]`.
///
/// It exposes the configurable one-handler feature before installation, while
/// [`IntoFeature`] remains the common installation protocol used by
/// [`Module::add`].
pub trait GeneratedFeature<S>: IntoFeature<S>
where
    S: Send + Sync + 'static,
{
    fn into_feature(self) -> Feature<S>;
}

/// Local configuration shortcuts for generated command feature values.
pub trait FeatureExt: Sized {
    fn guard<S, G>(self, guard: G) -> Feature<S>
    where
        S: Send + Sync + 'static,
        Self: GeneratedFeature<S>,
        G: Guard<S>,
    {
        self.into_feature().guard(guard)
    }

    fn before<S, B>(self, hook: B) -> Feature<S>
    where
        S: Send + Sync + 'static,
        Self: GeneratedFeature<S>,
        B: Before<S>,
    {
        self.into_feature().before(hook)
    }

    fn after<S, A>(self, hook: A) -> Feature<S>
    where
        S: Send + Sync + 'static,
        Self: GeneratedFeature<S>,
        A: After<S>,
    {
        self.into_feature().after(hook)
    }

    fn for_platform<S>(self, platform: PlatformId) -> Feature<S>
    where
        S: Send + Sync + 'static,
        Self: GeneratedFeature<S>,
    {
        self.into_feature().for_platform(platform)
    }

    fn for_bot<S>(self, bot: BotIdentity) -> Feature<S>
    where
        S: Send + Sync + 'static,
        Self: GeneratedFeature<S>,
    {
        self.into_feature().for_bot(bot)
    }

    fn block<S>(self, block: bool) -> Feature<S>
    where
        S: Send + Sync + 'static,
        Self: GeneratedFeature<S>,
    {
        self.into_feature().block(block)
    }

    fn continue_after<S>(self) -> Feature<S>
    where
        S: Send + Sync + 'static,
        Self: GeneratedFeature<S>,
    {
        self.into_feature().continue_after()
    }

    fn stop_after<S>(self) -> Feature<S>
    where
        S: Send + Sync + 'static,
        Self: GeneratedFeature<S>,
    {
        self.into_feature().stop_after()
    }

    fn shortcut<S>(self, shortcut: Shortcut) -> Feature<S>
    where
        S: Send + Sync + 'static,
        Self: GeneratedFeature<S>,
    {
        self.into_feature().shortcut(shortcut)
    }

    fn runtime_shortcuts<S>(self) -> Feature<S>
    where
        S: Send + Sync + 'static,
        Self: GeneratedFeature<S>,
    {
        self.into_feature().runtime_shortcuts()
    }

    fn completion<S>(self, completion: CompletionConfig) -> Feature<S>
    where
        S: Send + Sync + 'static,
        Self: GeneratedFeature<S>,
    {
        self.into_feature().completion(completion)
    }

    fn complete<S, F, C>(self, field: F, provider: C) -> Feature<S>
    where
        S: Send + Sync + 'static,
        Self: GeneratedFeature<S>,
        F: CommandFieldTag,
        C: DynamicCompleter<S>,
    {
        self.into_feature().complete(field, provider)
    }
}

impl<T> FeatureExt for T {}

impl<S> Feature<S>
where
    S: Send + Sync + 'static,
{
    fn new(definition: HandlerDefinition<S>) -> Self {
        Self {
            definition,
            completers: Vec::new(),
            errors: Vec::new(),
            runtime_shortcuts: false,
        }
    }

    #[must_use]
    pub fn event<E, H, T>(_event: E, handler: H) -> Self
    where
        E: EventTag,
        H: IntoHandler<T, S>,
    {
        Self::new(HandlerDefinition {
            selector: Selector::Event {
                event_type: E::TYPE,
                kind: E::TYPE.dispatch_kind(),
            },
            endpoint: EndpointKind::Handler(handler.into_endpoint()),
            guards: Vec::new(),
            before: Vec::new(),
            after: Vec::new(),
            scope: RouteScope::global(),
            default_block: false,
            branch_filter: None,
        })
    }

    #[must_use]
    pub fn message<H, T>(handler: H) -> Self
    where
        H: IntoHandler<T, S>,
    {
        Self::event(tags::Message, handler)
    }

    #[must_use]
    pub fn command<H, T>(command: Command, handler: H) -> Self
    where
        H: IntoHandler<T, S>,
    {
        Self::new(HandlerDefinition {
            selector: Selector::Command(command),
            endpoint: EndpointKind::Handler(handler.into_endpoint()),
            guards: Vec::new(),
            before: Vec::new(),
            after: Vec::new(),
            scope: RouteScope::global(),
            default_block: true,
            branch_filter: None,
        })
    }

    #[must_use]
    pub fn command_tree<C, H, T>(handler: H) -> Self
    where
        C: crate::command::CommandTree,
        H: IntoHandler<T, S>,
    {
        Self::command(C::command(), handler)
    }

    #[must_use]
    pub fn command_branch<B, H, T>(_branch: B, handler: H) -> Self
    where
        B: crate::CommandBranchTag,
        H: IntoHandler<T, S>,
    {
        Self::new(HandlerDefinition {
            selector: Selector::Command(<B::Command as crate::command::CommandTree>::command()),
            endpoint: EndpointKind::Handler(handler.into_endpoint()),
            guards: Vec::new(),
            before: Vec::new(),
            after: Vec::new(),
            scope: RouteScope::global(),
            default_block: true,
            branch_filter: Some((
                B::PATH.iter().map(|value| Arc::from(*value)).collect(),
                B::MATCH_DESCENDANTS,
            )),
        })
    }

    #[must_use]
    pub fn interaction<H, T>(custom_id: impl Into<Arc<str>>, handler: H) -> Self
    where
        H: IntoHandler<T, S>,
    {
        Self::new(HandlerDefinition {
            selector: Selector::Interaction(custom_id.into()),
            endpoint: EndpointKind::Handler(handler.into_endpoint()),
            guards: Vec::new(),
            before: Vec::new(),
            after: Vec::new(),
            scope: RouteScope::global(),
            default_block: true,
            branch_filter: None,
        })
    }

    #[must_use]
    pub fn native<H, T>(kind: impl Into<Arc<str>>, handler: H) -> Self
    where
        H: IntoHandler<T, S>,
    {
        Self::new(HandlerDefinition {
            selector: Selector::Native(kind.into()),
            endpoint: EndpointKind::Handler(handler.into_endpoint()),
            guards: Vec::new(),
            before: Vec::new(),
            after: Vec::new(),
            scope: RouteScope::global(),
            default_block: false,
            branch_filter: None,
        })
    }

    #[must_use]
    pub fn guard<G>(mut self, guard: G) -> Self
    where
        G: Guard<S>,
    {
        self.definition.guards.push(Arc::new(guard));
        self
    }

    #[must_use]
    pub fn before<B>(mut self, hook: B) -> Self
    where
        B: Before<S>,
    {
        self.definition.before.push(Arc::new(hook));
        self
    }

    #[must_use]
    pub fn after<A>(mut self, hook: A) -> Self
    where
        A: After<S>,
    {
        self.definition.after.push(Arc::new(hook));
        self
    }

    #[must_use]
    pub fn for_platform(mut self, platform: PlatformId) -> Self {
        let restriction = RouteScope::for_platform(platform);
        match self.definition.scope.intersect(&restriction) {
            Ok(scope) => self.definition.scope = scope,
            Err(error) => self.errors.push(error),
        }
        self
    }

    #[must_use]
    pub fn for_bot(mut self, bot: BotIdentity) -> Self {
        let restriction = RouteScope::for_bot(bot);
        match self.definition.scope.intersect(&restriction) {
            Ok(scope) => self.definition.scope = scope,
            Err(error) => self.errors.push(error),
        }
        self
    }

    #[must_use]
    pub const fn block(mut self, block: bool) -> Self {
        self.definition.default_block = block;
        self
    }

    #[must_use]
    pub const fn continue_after(self) -> Self {
        self.block(false)
    }

    #[must_use]
    pub const fn stop_after(self) -> Self {
        self.block(true)
    }

    #[must_use]
    pub fn shortcut(mut self, shortcut: Shortcut) -> Self {
        match &mut self.definition.selector {
            Selector::Command(command) => *command = command.clone().shortcut(shortcut),
            _ => self
                .errors
                .push("shortcuts can only be attached to command features".into()),
        }
        self
    }

    /// Enables the bounded runtime shortcut registry for this command.
    #[must_use]
    pub const fn runtime_shortcuts(mut self) -> Self {
        self.runtime_shortcuts = true;
        self
    }

    #[must_use]
    pub fn completion(mut self, completion: CompletionConfig) -> Self {
        match &mut self.definition.selector {
            Selector::Command(command) => *command = command.clone().completion(completion),
            _ => self
                .errors
                .push("completion can only be attached to command features".into()),
        }
        self
    }

    #[must_use]
    pub fn complete<F, C>(mut self, _field: F, provider: C) -> Self
    where
        F: CommandFieldTag,
        C: DynamicCompleter<S>,
    {
        let branch = self
            .definition
            .branch_filter
            .as_ref()
            .map_or(&[][..], |(path, _)| path.as_ref());
        let branch_names = branch.iter().map(AsRef::as_ref).collect::<Vec<_>>();
        match &self.definition.selector {
            Selector::Command(command) => match command.field_id(&branch_names, F::NAME) {
                Some(field) => self.completers.push(CompleterBinding {
                    command: command.id(),
                    field,
                    provider: Arc::new(provider),
                }),
                None => self.errors.push(format!(
                    "command `{}` has no field `{}` on branch `{}`",
                    command.name(),
                    F::NAME,
                    branch_names.join(" "),
                )),
            },
            _ => self
                .errors
                .push("dynamic completion can only be attached to command features".into()),
        }
        self
    }

    /// Converts this one-handler authoring value into an ordinary flat module.
    #[must_use]
    pub fn into_module(self) -> Module<S> {
        let mut module = Module::new();
        module.handlers.push(self.definition);
        module.scope_errors.extend(self.errors);
        module.runtime_shortcuts = self.runtime_shortcuts;
        for binding in self.completers {
            if module
                .completers
                .insert((binding.command, binding.field), binding.provider)
                .is_some()
            {
                module.scope_errors.push(format!(
                    "more than one dynamic completer is registered for command {:016x}, field {:08x}",
                    binding.command.0,
                    binding.field.0,
                ));
            }
        }
        module
    }
}

impl<S> IntoFeature<S> for Feature<S>
where
    S: Send + Sync + 'static,
{
    fn install(self, module: Module<S>) -> Module<S> {
        module.include(self.into_module())
    }
}

impl<S> IntoFeature<S> for Module<S>
where
    S: Send + Sync + 'static,
{
    fn install(self, module: Module<S>) -> Module<S> {
        module.include(self)
    }
}

impl Command {
    /// Binds this command and an ordinary async function into one locally
    /// configurable feature.
    #[must_use]
    pub fn handle<S, H, T>(self, handler: H) -> Feature<S>
    where
        S: Send + Sync + 'static,
        H: IntoHandler<T, S>,
    {
        Feature::command(self, handler)
    }
}

impl<S> Default for Module<S>
where
    S: Send + Sync + 'static,
{
    fn default() -> Self {
        Self::new()
    }
}

impl<S> Module<S>
where
    S: Send + Sync + 'static,
{
    #[must_use]
    pub fn new() -> Self {
        Self {
            handlers: Vec::new(),
            guards: Vec::new(),
            before: Vec::new(),
            after: Vec::new(),
            default_scope: RouteScope::global(),
            scope_errors: Vec::new(),
            has_help: false,
            runtime_shortcuts: false,
            overlays: Vec::new(),
            completers: HashMap::new(),
        }
    }

    /// Installs one generated or manually configured Bot feature.
    #[must_use]
    #[allow(
        clippy::should_implement_trait,
        reason = "`add` installs a feature into this fluent module builder; it is not arithmetic"
    )]
    pub fn add<F>(self, feature: F) -> Self
    where
        F: crate::IntoFeature<S>,
    {
        feature.install(self)
    }

    /// Handles one exact public event type.
    #[must_use]
    pub fn on<E, H, T>(self, event: E, handler: H) -> Self
    where
        E: EventTag,
        H: IntoHandler<T, S>,
    {
        self.add(Feature::event(event, handler))
    }

    /// Handles every ordinary message event.
    #[must_use]
    pub fn message<H, T>(self, handler: H) -> Self
    where
        H: IntoHandler<T, S>,
    {
        self.add(Feature::message(handler))
    }

    /// Handles one strongly typed command.
    #[must_use]
    pub fn command<H, T>(self, command: Command, handler: H) -> Self
    where
        H: IntoHandler<T, S>,
    {
        self.add(Feature::command(command, handler))
    }

    /// Handles a complete command grammar generated by `#[derive(BotCommand)]`.
    #[must_use]
    pub fn command_tree<C, H, T>(self, handler: H) -> Self
    where
        C: crate::command::CommandTree,
        H: IntoHandler<T, S>,
    {
        self.add(Feature::command_tree::<C, H, T>(handler))
    }

    /// Registers a handler for one statically generated branch of a command tree.
    #[must_use]
    pub fn command_branch<B, H, T>(self, branch: B, handler: H) -> Self
    where
        B: crate::CommandBranchTag,
        H: IntoHandler<T, S>,
    {
        self.add(Feature::command_branch(branch, handler))
    }

    /// Handles one interaction custom identifier.
    #[must_use]
    pub fn interaction<H, T>(self, custom_id: impl Into<Arc<str>>, handler: H) -> Self
    where
        H: IntoHandler<T, S>,
    {
        self.add(Feature::interaction(custom_id, handler))
    }

    /// Handles one platform-native lifecycle identifier.
    #[must_use]
    pub fn native<H, T>(self, kind: impl Into<Arc<str>>, handler: H) -> Self
    where
        H: IntoHandler<T, S>,
    {
        self.add(Feature::native(kind, handler))
    }

    /// Includes another feature module in registration order.
    ///
    /// No command prefix, route tree, runtime, or event bus is introduced.
    #[must_use]
    pub fn include(mut self, mut other: Self) -> Self {
        other.bake_hooks();
        self.scope_errors.append(&mut other.scope_errors);
        if !self.default_scope.is_global() {
            for handler in &mut other.handlers {
                match handler.scope.intersect(&self.default_scope) {
                    Ok(scope) => handler.scope = scope,
                    Err(error) => self.scope_errors.push(error),
                }
            }
        }
        if self.has_help && other.has_help {
            let existing_help_scopes = self
                .handlers
                .iter()
                .filter(|handler| matches!(&handler.endpoint, EndpointKind::Help))
                .map(|handler| handler.scope.clone())
                .collect::<Vec<_>>();
            other.handlers.retain(|handler| {
                !matches!(&handler.endpoint, EndpointKind::Help)
                    || !existing_help_scopes
                        .iter()
                        .any(|scope| scope.overlaps(&handler.scope))
            });
        }
        self.has_help |= other.has_help;
        self.runtime_shortcuts |= other.runtime_shortcuts;
        self.overlays.append(&mut other.overlays);
        for (key, provider) in other.completers.drain() {
            if self.completers.insert(key, provider).is_some() {
                self.scope_errors.push(format!(
                    "more than one dynamic completer is registered for command {:016x}, field {:08x}",
                    key.0.0,
                    key.1.0,
                ));
            }
        }
        self.handlers.append(&mut other.handlers);
        self
    }

    /// Enables the bounded runtime shortcut registry for this application.
    /// Added shortcuts select only their owning command IDs before parsing;
    /// they do not move unrelated commands onto the broad message path.
    #[must_use]
    pub const fn runtime_shortcuts(mut self) -> Self {
        self.runtime_shortcuts = true;
        self
    }

    pub(crate) const fn runtime_shortcuts_enabled(&self) -> bool {
        self.runtime_shortcuts
    }

    /// Applies a data-only metadata overlay to matching commands regardless of
    /// whether the overlay is declared before or after included modules.
    #[must_use]
    pub fn command_overlay(mut self, overlay: crate::CommandOverlay) -> Self {
        self.overlays.push(overlay);
        self
    }

    /// Applies an async admission rule to every handler in this module,
    /// including handlers from included modules.
    #[must_use]
    pub fn guard<G>(mut self, guard: G) -> Self
    where
        G: Guard<S>,
    {
        self.guards.push(Arc::new(guard));
        self
    }

    /// Runs an async hook before each matched handler.
    #[must_use]
    pub fn before<B>(mut self, hook: B) -> Self
    where
        B: Before<S>,
    {
        self.before.push(Arc::new(hook));
        self
    }

    /// Runs an async hook after each matched handler.
    #[must_use]
    pub fn after<A>(mut self, hook: A) -> Self
    where
        A: After<S>,
    {
        self.after.push(Arc::new(hook));
        self
    }

    /// Restricts every handler in this module to one platform, regardless of declaration order.
    #[must_use]
    pub fn for_platform(mut self, platform: PlatformId) -> Self {
        let restriction = RouteScope::for_platform(platform);
        self.restrict_scope(&restriction);
        self
    }

    /// Restricts every handler in this module to one bot, regardless of declaration order.
    #[must_use]
    pub fn for_bot(mut self, bot: BotIdentity) -> Self {
        let restriction = RouteScope::for_bot(bot);
        self.restrict_scope(&restriction);
        self
    }

    /// Adds `/help [command]`, generated from the same schemas used for parsing.
    #[must_use]
    pub fn help(self) -> Self {
        self.help_command(
            crate::command("help")
                .alias("帮助")
                .description("显示命令目录或某个命令的详细帮助"),
        )
    }

    #[must_use]
    pub fn help_command(mut self, command: Command) -> Self {
        if self.handlers.iter().any(|handler| {
            matches!(&handler.endpoint, EndpointKind::Help)
                && handler.scope.overlaps(&self.default_scope)
        }) {
            return self;
        }
        self.has_help = true;
        self.handlers.push(HandlerDefinition {
            selector: Selector::Command(command),
            endpoint: EndpointKind::Help,
            guards: Vec::new(),
            before: Vec::new(),
            after: Vec::new(),
            scope: self.default_scope.clone(),
            default_block: true,
            branch_filter: None,
        });
        self
    }

    #[must_use]
    pub fn catalog(&self) -> CommandCatalog {
        let mut seen = std::collections::HashSet::new();
        CommandCatalog::scoped(self.handlers.iter().filter_map(|handler| {
            if let Selector::Command(command) = &handler.selector {
                let command = self.apply_overlays_to(command.clone());
                let key = (command.id(), handler.scope.clone());
                if seen.insert(key) {
                    Some((command, handler.scope.clone()))
                } else {
                    None
                }
            } else {
                None
            }
        }))
    }

    pub(crate) fn install_completers(
        &self,
        target: &mut HashMap<(CommandId, CommandFieldId), Arc<dyn DynamicCompleter<S>>>,
    ) -> Result<(), BuildError> {
        for (key, provider) in &self.completers {
            if target.insert(*key, Arc::clone(provider)).is_some() {
                return Err(BuildError::InvalidRoute(format!(
                    "more than one dynamic completer is registered for command {:016x}, field {:08x}",
                    key.0.0,
                    key.1.0,
                )));
            }
        }
        Ok(())
    }

    fn apply_overlays_to(&self, mut command: Command) -> Command {
        for overlay in &self.overlays {
            if overlay.matches(&command) {
                command = overlay.apply(command);
            }
        }
        command
    }

    fn apply_overlays(&mut self) {
        let overlays = self.overlays.clone();
        for handler in &mut self.handlers {
            let Selector::Command(command) = &mut handler.selector else {
                continue;
            };
            for overlay in &overlays {
                if overlay.matches(command) {
                    *command = overlay.apply(command.clone());
                }
            }
        }
    }

    pub(crate) fn into_handlers(mut self) -> Result<Vec<Arc<dyn ErasedHandler<S>>>, BuildError> {
        self.apply_overlays();
        self.overlays.clear();
        if let Some(error) = self.scope_errors.first().cloned() {
            return Err(BuildError::InvalidRoute(error));
        }
        validate_command_conflicts(&self.handlers).map_err(BuildError::InvalidRoute)?;
        self.bake_hooks();
        let catalog = Arc::new(self.catalog());
        let mut output: Vec<Arc<dyn ErasedHandler<S>>> = Vec::new();

        for definition in self.handlers {
            let endpoint: Arc<dyn Endpoint<S>> = match definition.endpoint {
                EndpointKind::Handler(endpoint) => endpoint,
                EndpointKind::Help => Arc::new(HelpEndpoint::<S> {
                    catalog: Arc::clone(&catalog),
                    _state: PhantomData,
                }),
            };
            match definition.selector {
                Selector::Event { event_type, kind } => {
                    output.push(Arc::new(ModuleHandler {
                        spec: RouteSpec::Event(event_type),
                        event_kind: kind,
                        scope: definition.scope,
                        endpoint,
                        guards: definition.guards.into(),
                        before: definition.before.into(),
                        after: definition.after.into(),
                        command: None,
                        default_block: definition.default_block,
                        branch_filter: definition.branch_filter.clone(),
                    }));
                }
                Selector::Interaction(custom_id) => {
                    output.push(Arc::new(ModuleHandler {
                        spec: RouteSpec::Interaction(custom_id),
                        event_kind: DispatchKind::Interaction,
                        scope: definition.scope,
                        endpoint,
                        guards: definition.guards.into(),
                        before: definition.before.into(),
                        after: definition.after.into(),
                        command: None,
                        default_block: definition.default_block,
                        branch_filter: definition.branch_filter.clone(),
                    }));
                }
                Selector::Native(kind) => {
                    output.push(Arc::new(ModuleHandler {
                        spec: RouteSpec::Native(kind),
                        event_kind: DispatchKind::Native,
                        scope: definition.scope,
                        endpoint,
                        guards: definition.guards.into(),
                        before: definition.before.into(),
                        after: definition.after.into(),
                        command: None,
                        default_block: definition.default_block,
                        branch_filter: definition.branch_filter.clone(),
                    }));
                }
                Selector::Command(command) => {
                    command.validate().map_err(BuildError::InvalidRoute)?;
                    let specs = command.fast_route_keys().map_or_else(
                        || vec![RouteSpec::Event(EventType::Message)],
                        |keys| keys.into_iter().map(RouteSpec::Command).collect(),
                    );
                    for spec in specs {
                        output.push(Arc::new(ModuleHandler {
                            spec,
                            event_kind: DispatchKind::Message,
                            scope: definition.scope.clone(),
                            endpoint: Arc::clone(&endpoint),
                            guards: definition.guards.clone().into(),
                            before: definition.before.clone().into(),
                            after: definition.after.clone().into(),
                            command: Some(command.clone()),
                            default_block: definition.default_block,
                            branch_filter: definition.branch_filter.clone(),
                        }));
                    }
                    output.push(Arc::new(ModuleHandler {
                        spec: RouteSpec::Event(EventType::Interaction),
                        event_kind: DispatchKind::Interaction,
                        scope: definition.scope,
                        endpoint,
                        guards: definition.guards.into(),
                        before: definition.before.into(),
                        after: definition.after.into(),
                        command: Some(command),
                        default_block: definition.default_block,
                        branch_filter: definition.branch_filter.clone(),
                    }));
                }
            }
        }
        if !catalog.commands().is_empty() {
            output.push(Arc::new(ModuleHandler {
                spec: RouteSpec::Event(EventType::LifecycleSuggestionRequested),
                event_kind: EventType::LifecycleSuggestionRequested.dispatch_kind(),
                scope: RouteScope::global(),
                endpoint: Arc::new(SuggestionEndpoint::<S> {
                    catalog,
                    _state: PhantomData,
                }),
                guards: Arc::from([]),
                before: Arc::from([]),
                after: Arc::from([]),
                command: None,
                default_block: true,
                branch_filter: None,
            }));
        }
        Ok(output)
    }

    fn restrict_scope(&mut self, restriction: &RouteScope) {
        for handler in &mut self.handlers {
            match handler.scope.intersect(restriction) {
                Ok(scope) => handler.scope = scope,
                Err(error) => self.scope_errors.push(error),
            }
        }
        match self.default_scope.intersect(restriction) {
            Ok(scope) => self.default_scope = scope,
            Err(error) => self.scope_errors.push(error),
        }
    }

    fn bake_hooks(&mut self) {
        if self.guards.is_empty() && self.before.is_empty() && self.after.is_empty() {
            return;
        }
        for handler in &mut self.handlers {
            if !self.guards.is_empty() {
                let mut guards = self.guards.clone();
                guards.append(&mut handler.guards);
                handler.guards = guards;
            }
            if !self.before.is_empty() {
                let mut before = self.before.clone();
                before.append(&mut handler.before);
                handler.before = before;
            }
            if !self.after.is_empty() {
                handler.after.extend(self.after.iter().cloned());
            }
        }
        self.guards.clear();
        self.before.clear();
        self.after.clear();
    }
}

fn validate_command_conflicts<S>(handlers: &[HandlerDefinition<S>]) -> Result<(), String>
where
    S: Send + Sync + 'static,
{
    let commands = handlers.iter().filter_map(|handler| {
        let Selector::Command(command) = &handler.selector else {
            return None;
        };
        Some((command, &handler.scope))
    });

    let mut globals = HashMap::<Arc<str>, Arc<str>>::new();
    let mut platforms = HashMap::<(PlatformId, Arc<str>), Arc<str>>::new();
    let mut bots = HashMap::<(BotIdentity, Arc<str>), Arc<str>>::new();
    let mut seen_commands = std::collections::HashSet::new();
    let commands = commands
        .filter(|(command, scope)| seen_commands.insert((command.id(), (*scope).clone())))
        .collect::<Vec<_>>();
    for (command, _) in &commands {
        command.validate()?;
    }

    for (command, _scope) in commands
        .iter()
        .copied()
        .filter(|(_, scope)| scope.is_global())
    {
        for key in command.registration_keys() {
            if let Some(previous) = globals.insert(key.clone(), Arc::from(command.name())) {
                return Err(format!(
                    "command `{}` conflicts with `{previous}` in the global Bot scope",
                    command.name(),
                ));
            }
        }
    }

    for (command, scope) in commands
        .iter()
        .copied()
        .filter(|(_, scope)| scope.bot.is_none() && scope.platform.is_some())
    {
        let platform = scope
            .platform
            .as_ref()
            .expect("platform-scoped command has a platform");
        for key in command.registration_keys() {
            if let Some(previous) = globals.get(&key) {
                return Err(format!(
                    "command `{}` for platform {platform} conflicts with global command `{previous}`",
                    command.name(),
                ));
            }
            let map_key = (platform.clone(), key);
            if let Some(previous) = platforms.insert(map_key, Arc::from(command.name())) {
                return Err(format!(
                    "command `{}` conflicts with `{previous}` for platform {platform}",
                    command.name(),
                ));
            }
        }
    }

    for (command, scope) in commands
        .iter()
        .copied()
        .filter(|(_, scope)| scope.bot.is_some())
    {
        let bot = scope.bot.as_ref().expect("bot-scoped command has a bot");
        for key in command.registration_keys() {
            if let Some(previous) = globals.get(&key) {
                return Err(format!(
                    "command `{}` for bot {}:{} conflicts with global command `{previous}`",
                    command.name(),
                    bot.platform,
                    bot.bot,
                ));
            }
            if let Some(previous) = platforms.get(&(bot.platform.clone(), key.clone())) {
                return Err(format!(
                    "command `{}` for bot {}:{} conflicts with platform command `{previous}`",
                    command.name(),
                    bot.platform,
                    bot.bot,
                ));
            }
            let map_key = (bot.clone(), key);
            if let Some(previous) = bots.insert(map_key, Arc::from(command.name())) {
                return Err(format!(
                    "command `{}` conflicts with `{previous}` for bot {}:{}",
                    command.name(),
                    bot.platform,
                    bot.bot,
                ));
            }
        }
    }

    Ok(())
}

// Command selectors are stored once per handler; keeping commands inline avoids
// an allocation on every registration.
#[allow(clippy::large_enum_variant)]
enum Selector {
    Event {
        event_type: EventType,
        kind: DispatchKind,
    },
    Command(Command),
    Interaction(Arc<str>),
    Native(Arc<str>),
}

enum EndpointKind<S>
where
    S: Send + Sync + 'static,
{
    Handler(Arc<dyn Endpoint<S>>),
    Help,
}

struct HandlerDefinition<S>
where
    S: Send + Sync + 'static,
{
    selector: Selector,
    endpoint: EndpointKind<S>,
    guards: Vec<SharedGuard<S>>,
    before: Vec<SharedBefore<S>>,
    after: Vec<SharedAfter<S>>,
    scope: RouteScope,
    default_block: bool,
    branch_filter: Option<(Arc<[Arc<str>]>, bool)>,
}

struct ModuleHandler<S>
where
    S: Send + Sync + 'static,
{
    spec: RouteSpec,
    event_kind: DispatchKind,
    scope: RouteScope,
    endpoint: Arc<dyn Endpoint<S>>,
    guards: Arc<[SharedGuard<S>]>,
    before: Arc<[SharedBefore<S>]>,
    after: Arc<[SharedAfter<S>]>,
    command: Option<Command>,
    default_block: bool,
    branch_filter: Option<(Arc<[Arc<str>]>, bool)>,
}

fn bind_delivery<S>(context: &Context<S>, outcome: Outcome) -> Outcome
where
    S: Send + Sync + 'static,
{
    let pipeline: Arc<dyn crate::authoring::ErasedDeliveryPipeline> =
        Arc::new(crate::authoring::BoundDeliveryPipeline {
            runtime: context.authoring_arc(),
            context: context.clone(),
        });
    outcome.with_delivery_pipeline(pipeline)
}

impl<S> ErasedHandler<S> for ModuleHandler<S>
where
    S: Send + Sync + 'static,
{
    fn route_spec(&self) -> RouteSpec {
        self.spec.clone()
    }

    fn route_scope(&self) -> RouteScope {
        self.scope.clone()
    }

    fn event_kind(&self) -> DispatchKind {
        self.event_kind
    }

    fn default_block(&self) -> bool {
        self.default_block
    }

    fn command_id(&self) -> Option<crate::CommandId> {
        self.command.as_ref().map(Command::id)
    }

    fn call(&self, call: HandlerCall<S>) -> BoxFuture<'static, HandlerResult<Outcome>> {
        let HandlerCall {
            event,
            state,
            bot,
            sessions,
            shutdown,
            authoring,
            command_input,
        } = call;
        let endpoint = Arc::clone(&self.endpoint);
        let guards = Arc::clone(&self.guards);
        let before = Arc::clone(&self.before);
        let after = Arc::clone(&self.after);
        let command = self.command.clone();
        let branch_filter = self.branch_filter.clone();

        Box::pin(async move {
            let base_context = Context::new(
                Arc::clone(&event),
                Arc::clone(&state),
                bot.clone(),
                sessions.clone(),
                shutdown.clone(),
                None,
                Arc::clone(&authoring),
            );
            let command = if let Some(command) = command {
                if !authoring.registry.is_enabled(command.id()) {
                    return Ok(Outcome::continue_());
                }
                match match_command_event(
                    &command,
                    event.event(),
                    &base_context,
                    command_input.as_deref(),
                )
                .await
                {
                    Ok(Some(result)) => Some(result),
                    Ok(None) => return Ok(Outcome::continue_()),
                    Err(CommandEventError::Parse(error)) => {
                        let outcome =
                            command_parse_outcome(&base_context, &command, &[], error).await?;
                        return Ok(bind_delivery(&base_context, outcome));
                    }
                    Err(CommandEventError::Handler(error)) => return Err(error),
                }
            } else {
                None
            };
            if let (Some((filter, descendants)), Some(command)) = (&branch_filter, &command) {
                let matches = if *descendants {
                    command.branch_names().len() >= filter.len()
                        && command
                            .branch_names()
                            .iter()
                            .take(filter.len())
                            .zip(filter.iter())
                            .all(|(actual, expected)| actual.eq_ignore_ascii_case(expected))
                } else {
                    let expected = filter.iter().map(AsRef::as_ref).collect::<Vec<_>>();
                    command.is_branch(&expected)
                };
                if !matches {
                    return Ok(Outcome::continue_());
                }
            }

            let mut context =
                Context::new(event, state, bot, sessions, shutdown, command, authoring);

            // Admission runs before interactive completion. An unauthorized or
            // rate-limited user must never be prompted for missing arguments.
            for guard in guards.iter() {
                match guard.check(context.clone()).await? {
                    GuardDecision::Allow => {}
                    GuardDecision::Skip => return Ok(Outcome::continue_()),
                    GuardDecision::Deny(outcome) => {
                        return Ok(bind_delivery(
                            &context,
                            outcome.with_propagation(crate::Propagation::Stop),
                        ));
                    }
                }
            }

            if let Some((input, cursor)) = explicit_completion_input(context.event()) {
                if context.command().is_some() {
                    let outcome = command_completion_outcome(&context, &input, cursor).await?;
                    return Ok(bind_delivery(&context, outcome));
                }
            }
            if context.command().is_some() {
                match prepare_command(context.clone()).await? {
                    CommandPreparation::Ready(ready) => context = ready,
                    CommandPreparation::Respond(outcome) => {
                        return Ok(bind_delivery(&context, outcome));
                    }
                }
            }
            for hook in before.iter() {
                hook.call(context.clone()).await?;
            }

            let mut outcome = endpoint.call(context.clone()).await?;
            for hook in after.iter() {
                outcome = hook.call(context.clone(), outcome).await?;
            }
            Ok(bind_delivery(&context, outcome))
        })
    }
}

struct HelpEndpoint<S>
where
    S: Send + Sync + 'static,
{
    catalog: Arc<CommandCatalog>,
    _state: PhantomData<fn() -> S>,
}

impl<S> Endpoint<S> for HelpEndpoint<S>
where
    S: Send + Sync + 'static,
{
    fn call(&self, context: Context<S>) -> BoxFuture<'static, HandlerResult<Outcome>> {
        let catalog = self
            .catalog
            .for_identity(context.bot_identity())
            .enabled(&context.authoring().registry);
        let query = context
            .command()
            .map(|command| command.text_values().collect::<Vec<_>>().join(" "))
            .filter(|query| !query.is_empty());
        Box::pin(async move {
            let output = catalog.output(query.as_deref());
            let message = context.authoring().render(&context, output).await?;
            Ok(Outcome::new().reply(message))
        })
    }
}

struct SuggestionEndpoint<S>
where
    S: Send + Sync + 'static,
{
    catalog: Arc<CommandCatalog>,
    _state: PhantomData<fn() -> S>,
}

impl<S> Endpoint<S> for SuggestionEndpoint<S>
where
    S: Send + Sync + 'static,
{
    fn call(&self, context: Context<S>) -> BoxFuture<'static, HandlerResult<Outcome>> {
        let catalog = self
            .catalog
            .for_identity(context.bot_identity())
            .enabled(&context.authoring().registry);
        Box::pin(async move {
            let Event::LifecycleEvent(oxidebot_core::event::LifecycleEvent::SuggestionRequested(
                request,
            )) = context.event()
            else {
                return Ok(Outcome::continue_());
            };
            let request = request.clone();
            let mut suggestions = catalog.native_suggestions(&request);
            let command = request
                .command_id
                .as_deref()
                .and_then(|id| catalog.find_by_id(id))
                .or_else(|| {
                    request
                        .command_name
                        .as_deref()
                        .and_then(|name| catalog.find(name))
                });
            if let (Some(command), Some(field)) = (command, request.field_id.as_deref()) {
                let field = field
                    .trim_start_matches("oxidebot:")
                    .parse::<u32>()
                    .ok()
                    .map(crate::CommandFieldId);
                if let Some(field) = field {
                    let input = CompletionInput {
                        command: command.clone(),
                        field,
                        partial: Arc::from(request.query.as_str()),
                        replace: SourceSpan::default(),
                        locale: request.locale.as_deref().map(Arc::from),
                        limit: request.limit.unwrap_or(25).min(100) as usize,
                    };
                    let dynamic = context.authoring().complete(&context, input).await?;
                    let offset = suggestions.len();
                    suggestions.extend(
                        dynamic.into_iter().enumerate().map(|(index, item)| {
                            item.into_suggestion(offset.saturating_add(index))
                        }),
                    );
                    suggestions.truncate(request.limit.unwrap_or(25).min(100) as usize);
                }
            }
            context
                .bot()?
                .answer_suggestion_request(request, suggestions, None)
                .await
                .map_err(|error| HandlerError::Api(error.to_string()))?;
            Ok(Outcome::stop())
        })
    }
}

fn explicit_completion_input(event: &Event) -> Option<(String, usize)> {
    let Event::MessageEvent(message) = event else {
        return None;
    };
    let raw = message.message.get_raw_text();
    let trimmed = raw.trim_end();
    let input = trimmed.strip_suffix('?')?;
    if !input.chars().last().is_some_and(char::is_whitespace) {
        return None;
    }
    let input = input.trim_end().to_owned();
    let cursor = input.len();
    Some((input, cursor))
}

async fn command_completion_outcome<S>(
    context: &Context<S>,
    input: &str,
    cursor: usize,
) -> HandlerResult<Outcome>
where
    S: Send + Sync + 'static,
{
    let Some(result) = context.command() else {
        return Ok(Outcome::continue_());
    };
    let locale = context.authoring().locale(context).await;
    let mut items = result.command().suggest(input, cursor, locale.as_deref());
    let dynamic_fields = items
        .iter()
        .filter_map(|item| item.field_id.map(|field| (field, item.replace)))
        .collect::<Vec<_>>();
    for (field, replace) in dynamic_fields {
        let partial = input
            .get(replace.start.min(input.len())..replace.end.min(input.len()))
            .unwrap_or_default();
        let mut dynamic = context
            .authoring()
            .complete(
                context,
                CompletionInput {
                    command: result.command().clone(),
                    field,
                    partial: Arc::from(partial),
                    replace,
                    locale: locale.clone(),
                    limit: 25,
                },
            )
            .await?;
        items.append(&mut dynamic);
    }
    let mut seen = std::collections::HashSet::new();
    items.retain(|item| seen.insert((item.value.clone(), item.replace.start, item.replace.end)));
    items.truncate(25);
    let output = if items.is_empty() {
        CommandOutput::Message(oxidebot_core::Message::text(
            if locale
                .as_deref()
                .is_some_and(|value| value.to_ascii_lowercase().starts_with("zh"))
            {
                "当前输入位置没有可用补全"
            } else {
                "No completions are available at the current input position"
            },
        ))
    } else {
        CommandOutput::Suggestions {
            items: items.into(),
        }
    };
    let message = context.authoring().render(context, output).await?;
    Ok(Outcome::stop().reply(message))
}

// The ready context is consumed immediately by the dispatcher, so boxing it
// would add an allocation to every successfully prepared command.
#[allow(clippy::large_enum_variant)]
enum CommandPreparation<S>
where
    S: Send + Sync + 'static,
{
    Ready(Context<S>),
    Respond(Outcome),
}

async fn prepare_command<S>(context: Context<S>) -> Result<CommandPreparation<S>, HandlerError>
where
    S: Send + Sync + 'static,
{
    let Some(mut result) = context.command().cloned() else {
        return Ok(CommandPreparation::Ready(context));
    };

    match result.parse_active() {
        Ok(arguments) => {
            return finalize_command(context, result, arguments).await;
        }
        Err(error) if error.missing_prompt().is_none() => {
            return Ok(CommandPreparation::Respond(
                command_match_error_outcome(&context, &result, error).await?,
            ));
        }
        Err(error)
            if result.completion_ref().is_none()
                || matches!(result.source(), crate::CommandSource::Native(_)) =>
        {
            return Ok(CommandPreparation::Respond(
                command_match_error_outcome(&context, &result, error).await?,
            ));
        }
        Err(_) => {}
    }

    let completion = result
        .completion_ref()
        .cloned()
        .expect("missing arguments reach completion only when it is configured");
    let dialogue = Dialogue::extract(&context)?
        .timeout(completion.timeout)
        .namespace(format!(
            "command:{:016x}:{}",
            result.command().id().0,
            result
                .branch_path()
                .last()
                .map_or(0, |branch| u64::from(branch.0))
        ))?;

    for _ in 0..completion.max_rounds {
        let error = match result.parse_active() {
            Ok(arguments) => {
                return finalize_command(context, result, arguments).await;
            }
            Err(error) => error,
        };
        let Some(prompt) = error.missing_prompt() else {
            return Ok(CommandPreparation::Respond(
                command_match_error_outcome(&context, &result, error).await?,
            ));
        };
        let missing_name = error
            .missing_name()
            .expect("a missing prompt always belongs to a missing argument")
            .to_owned();
        let mut prompt_message = oxidebot_core::Message::text(prompt);
        if let Some(argument) = result
            .schema()
            .find(&missing_name)
            .filter(|argument| argument.is_autocomplete())
        {
            let locale = context.authoring().locale(&context).await;
            let dynamic = context
                .authoring()
                .complete(
                    &context,
                    CompletionInput {
                        command: result.command().clone(),
                        field: argument.id(),
                        partial: Arc::from(""),
                        replace: SourceSpan::default(),
                        locale,
                        limit: 12,
                    },
                )
                .await?;
            if !dynamic.is_empty() {
                let suggestions = context
                    .authoring()
                    .render(
                        &context,
                        CommandOutput::Suggestions {
                            items: dynamic.into(),
                        },
                    )
                    .await?;
                prompt_message = prompt_message.then("\n");
                prompt_message.extend(suggestions.segments);
            }
        }
        let response = dialogue.ask_message(prompt_message).await?;
        let Event::MessageEvent(message) = response.event() else {
            return Err(HandlerError::internal(
                "command completion received a non-message event",
            ));
        };
        let raw_text = message.message.get_raw_text();
        if completion.is_cancelled(&raw_text) {
            return Ok(CommandPreparation::Respond(
                command_match_error_outcome(&context, &result, CommandParseError::Cancelled)
                    .await?,
            ));
        }
        let values = match tokenize_segments(&message.message.segments) {
            Ok(values) => values,
            Err(error) => {
                return Ok(CommandPreparation::Respond(
                    command_match_error_outcome(&context, &result, error).await?,
                ));
            }
        };
        result = result.with_answer(&missing_name, values);
    }

    match result.parse_active() {
        Ok(arguments) => finalize_command(context, result, arguments).await,
        Err(error) if error.missing_prompt().is_some() => Ok(CommandPreparation::Respond(
            command_match_error_outcome(&context, &result, CommandParseError::CompletionExhausted)
                .await?,
        )),
        Err(error) => Ok(CommandPreparation::Respond(
            command_match_error_outcome(&context, &result, error).await?,
        )),
    }
}

enum CommandEventError {
    Parse(CommandParseError),
    Handler(HandlerError),
}

impl From<CommandParseError> for CommandEventError {
    fn from(value: CommandParseError) -> Self {
        Self::Parse(value)
    }
}

impl From<HandlerError> for CommandEventError {
    fn from(value: HandlerError) -> Self {
        Self::Handler(value)
    }
}

async fn match_command_event<S>(
    command: &Command,
    event: &Event,
    context: &Context<S>,
    command_input: Option<&tokio::sync::OnceCell<RewriteInput>>,
) -> Result<Option<CommandResult>, CommandEventError>
where
    S: Send + Sync + 'static,
{
    match event {
        Event::MessageEvent(message_event) => {
            let shortcuts = context
                .authoring()
                .registry
                .runtime_shortcuts_for(command.id());
            if let Some(command_input) = command_input {
                let input = command_input
                    .get_or_try_init(|| async {
                        let mut message = explicit_completion_input(event)
                            .map(|(input, _)| oxidebot_core::Message::text(input))
                            .unwrap_or_else(|| message_event.message.clone());
                        for normalizer in context.authoring().normalizers.iter() {
                            message = normalizer.normalize(context, message).await?;
                        }
                        let mut input = RewriteInput {
                            message,
                            locale: event_locale(event).map(Arc::from),
                        };
                        for rewriter in context.authoring().rewriters.iter() {
                            input = rewriter.rewrite(context, input).await?;
                        }
                        Ok::<RewriteInput, HandlerError>(input)
                    })
                    .await?;
                return command
                    .match_message_with_shortcuts(&input.message, &shortcuts)
                    .map(|matched| matched.map(|matched| matched.with_locale(input.locale.clone())))
                    .map_err(Into::into);
            }
            let input = RewriteInput {
                message: explicit_completion_input(event)
                    .map(|(input, _)| oxidebot_core::Message::text(input))
                    .unwrap_or_else(|| message_event.message.clone()),
                locale: event_locale(event).map(Arc::from),
            };
            command
                .match_message_with_shortcuts(&input.message, &shortcuts)
                .map(|matched| matched.map(|matched| matched.with_locale(input.locale)))
                .map_err(Into::into)
        }
        Event::InteractionEvent(interaction)
            if interaction.kind == InteractionKind::Command && interaction.command.is_some() =>
        {
            command
                .match_invocation(
                    interaction
                        .command
                        .as_ref()
                        .expect("guarded interaction command exists"),
                )
                .map_err(Into::into)
        }
        _ => Ok(None),
    }
}

fn event_locale(event: &Event) -> Option<&str> {
    match event {
        Event::InteractionEvent(interaction) => interaction
            .command
            .as_ref()
            .and_then(|command| command.locale.as_deref())
            .or(interaction.locale.as_deref()),
        _ => None,
    }
}

async fn finalize_command<S>(
    mut context: Context<S>,
    result: CommandResult,
    arguments: crate::ParsedArguments,
) -> Result<CommandPreparation<S>, HandlerError>
where
    S: Send + Sync + 'static,
{
    let parsed = result.with_parsed(arguments);
    let parsed = context
        .authoring()
        .apply_command_middleware(&context, parsed)
        .await?;
    context.command = Some(parsed);
    Ok(CommandPreparation::Ready(context))
}

async fn command_match_error_outcome<S>(
    context: &Context<S>,
    result: &CommandResult,
    error: CommandParseError,
) -> Result<Outcome, HandlerError>
where
    S: Send + Sync + 'static,
{
    command_parse_outcome(context, result.command(), result.branch_names(), error).await
}

async fn command_parse_outcome<S>(
    context: &Context<S>,
    command: &Command,
    branch_names: &[Arc<str>],
    error: CommandParseError,
) -> Result<Outcome, HandlerError>
where
    S: Send + Sync + 'static,
{
    let output = CommandOutput::ParseError {
        command: command.clone(),
        branch_names: branch_names.to_vec().into(),
        error,
    };
    let message = context.authoring().render(context, output).await?;
    Ok(Outcome::stop().reply(message))
}
