use crate::{
    command::tokenize_segments,
    function::IntoHandler,
    handler::{ErasedHandler, RouteScope, RouteSpec},
    hooks::{
        After, Before, Endpoint, Guard, GuardDecision, SharedAfter, SharedBefore, SharedGuard,
    },
    BotHandle, BuildError, Command, CommandCatalog, CommandOutput, CommandParseError,
    CommandRenderer, CommandResult, Context, DefaultCommandRenderer, Dialogue, Extract,
    HandlerError, HandlerResult, Outcome, SessionRegistry, ShutdownSignal,
};
use futures_util::future::BoxFuture;
use oxidebot_core::{
    event::{
        kernel::{DispatchEnvelope, DispatchKind},
        tags, EventTag, EventType,
    },
    interaction::InteractionKind,
    BotIdentity, Event, PlatformId,
};
use std::{collections::HashMap, marker::PhantomData, sync::Arc};

/// A flat, reusable Bot feature module.
///
/// A module groups commands, event handlers, guards, and lifecycle hooks. It is
/// deliberately not a URL tree: multi-word commands are declared as ordinary
/// command names, and including another module never creates hidden nesting.
pub struct Module<S = ()>
where
    S: Send + Sync + 'static,
{
    handlers: Vec<HandlerDefinition<S>>,
    guards: Vec<SharedGuard<S>>,
    before: Vec<SharedBefore<S>>,
    after: Vec<SharedAfter<S>>,
    default_scope: RouteScope,
    scope_errors: Vec<String>,
    has_help: bool,
}

impl<S> Default for Module<S>
where
    S: Send + Sync + 'static,
{
    fn default() -> Self {
        Self::new()
    }
}

impl<S> Module<S>
where
    S: Send + Sync + 'static,
{
    #[must_use]
    pub fn new() -> Self {
        Self {
            handlers: Vec::new(),
            guards: Vec::new(),
            before: Vec::new(),
            after: Vec::new(),
            default_scope: RouteScope::global(),
            scope_errors: Vec::new(),
            has_help: false,
        }
    }

    /// Handles one exact public event type.
    #[must_use]
    pub fn on<E, H, T>(mut self, _event: E, handler: H) -> Self
    where
        E: EventTag,
        H: IntoHandler<T, S>,
    {
        self.handlers.push(HandlerDefinition {
            selector: Selector::Event {
                event_type: E::TYPE,
                kind: E::TYPE.dispatch_kind(),
            },
            endpoint: EndpointKind::Handler(handler.into_endpoint()),
            guards: Vec::new(),
            before: Vec::new(),
            after: Vec::new(),
            scope: self.default_scope.clone(),
            default_block: false,
        });
        self
    }

    /// Handles every ordinary message event.
    #[must_use]
    pub fn message<H, T>(self, handler: H) -> Self
    where
        H: IntoHandler<T, S>,
    {
        self.on(tags::Message, handler)
    }

    /// Handles one strongly typed command.
    #[must_use]
    pub fn command<H, T>(mut self, command: Command, handler: H) -> Self
    where
        H: IntoHandler<T, S>,
    {
        self.handlers.push(HandlerDefinition {
            selector: Selector::Command(command),
            endpoint: EndpointKind::Handler(handler.into_endpoint()),
            guards: Vec::new(),
            before: Vec::new(),
            after: Vec::new(),
            scope: self.default_scope.clone(),
            default_block: true,
        });
        self
    }

    /// Handles a complete command grammar generated by `#[derive(BotCommand)]`.
    #[must_use]
    pub fn command_tree<C, H, T>(self, handler: H) -> Self
    where
        C: crate::command::CommandTree,
        H: IntoHandler<T, S>,
    {
        self.command(C::command(), handler)
    }

    /// Handles one interaction custom identifier.
    #[must_use]
    pub fn interaction<H, T>(mut self, custom_id: impl Into<Arc<str>>, handler: H) -> Self
    where
        H: IntoHandler<T, S>,
    {
        self.handlers.push(HandlerDefinition {
            selector: Selector::Interaction(custom_id.into()),
            endpoint: EndpointKind::Handler(handler.into_endpoint()),
            guards: Vec::new(),
            before: Vec::new(),
            after: Vec::new(),
            scope: self.default_scope.clone(),
            default_block: true,
        });
        self
    }

    /// Handles one platform-native lifecycle identifier.
    #[must_use]
    pub fn native<H, T>(mut self, kind: impl Into<Arc<str>>, handler: H) -> Self
    where
        H: IntoHandler<T, S>,
    {
        self.handlers.push(HandlerDefinition {
            selector: Selector::Native(kind.into()),
            endpoint: EndpointKind::Handler(handler.into_endpoint()),
            guards: Vec::new(),
            before: Vec::new(),
            after: Vec::new(),
            scope: self.default_scope.clone(),
            default_block: false,
        });
        self
    }

    /// Includes another feature module in registration order.
    ///
    /// No command prefix, route tree, runtime, or event bus is introduced.
    #[must_use]
    pub fn include(mut self, mut other: Self) -> Self {
        other.bake_hooks();
        self.scope_errors.append(&mut other.scope_errors);
        if !self.default_scope.is_global() {
            for handler in &mut other.handlers {
                match handler.scope.intersect(&self.default_scope) {
                    Ok(scope) => handler.scope = scope,
                    Err(error) => self.scope_errors.push(error),
                }
            }
        }
        if self.has_help && other.has_help {
            let existing_help_scopes = self
                .handlers
                .iter()
                .filter(|handler| matches!(&handler.endpoint, EndpointKind::Help))
                .map(|handler| handler.scope.clone())
                .collect::<Vec<_>>();
            other.handlers.retain(|handler| {
                !matches!(&handler.endpoint, EndpointKind::Help)
                    || !existing_help_scopes
                        .iter()
                        .any(|scope| scope.overlaps(&handler.scope))
            });
        }
        self.has_help |= other.has_help;
        self.handlers.append(&mut other.handlers);
        self
    }

    /// Applies an async admission rule to every handler in this module,
    /// including handlers from included modules.
    #[must_use]
    pub fn guard<G>(mut self, guard: G) -> Self
    where
        G: Guard<S>,
    {
        self.guards.push(Arc::new(guard));
        self
    }

    /// Runs an async hook before each matched handler.
    #[must_use]
    pub fn before<B>(mut self, hook: B) -> Self
    where
        B: Before<S>,
    {
        self.before.push(Arc::new(hook));
        self
    }

    /// Runs an async hook after each matched handler.
    #[must_use]
    pub fn after<A>(mut self, hook: A) -> Self
    where
        A: After<S>,
    {
        self.after.push(Arc::new(hook));
        self
    }

    /// Restricts every handler in this module to one platform, regardless of declaration order.
    #[must_use]
    pub fn for_platform(mut self, platform: PlatformId) -> Self {
        let restriction = RouteScope::for_platform(platform);
        self.restrict_scope(&restriction);
        self
    }

    /// Restricts every handler in this module to one bot, regardless of declaration order.
    #[must_use]
    pub fn for_bot(mut self, bot: BotIdentity) -> Self {
        let restriction = RouteScope::for_bot(bot);
        self.restrict_scope(&restriction);
        self
    }

    /// Adds `/help [command]`, generated from the same schemas used for parsing.
    #[must_use]
    pub fn help(self) -> Self {
        self.help_command(
            crate::command("help")
                .alias("帮助")
                .description("显示命令目录或某个命令的详细帮助"),
        )
    }

    #[must_use]
    pub fn help_command(mut self, command: Command) -> Self {
        if self.handlers.iter().any(|handler| {
            matches!(&handler.endpoint, EndpointKind::Help)
                && handler.scope.overlaps(&self.default_scope)
        }) {
            return self;
        }
        self.has_help = true;
        self.handlers.push(HandlerDefinition {
            selector: Selector::Command(command),
            endpoint: EndpointKind::Help,
            guards: Vec::new(),
            before: Vec::new(),
            after: Vec::new(),
            scope: self.default_scope.clone(),
            default_block: true,
        });
        self
    }

    #[must_use]
    pub fn catalog(&self) -> CommandCatalog {
        CommandCatalog::scoped(self.handlers.iter().filter_map(|handler| {
            if let Selector::Command(command) = &handler.selector {
                Some((command.clone(), handler.scope.clone()))
            } else {
                None
            }
        }))
    }

    pub(crate) fn into_handlers(mut self) -> Result<Vec<Arc<dyn ErasedHandler<S>>>, BuildError> {
        if let Some(error) = self.scope_errors.first().cloned() {
            return Err(BuildError::InvalidRoute(error));
        }
        validate_command_conflicts(&self.handlers).map_err(BuildError::InvalidRoute)?;
        self.bake_hooks();
        let catalog = Arc::new(self.catalog());
        let mut output: Vec<Arc<dyn ErasedHandler<S>>> = Vec::new();

        for definition in self.handlers {
            let endpoint: Arc<dyn Endpoint<S>> = match definition.endpoint {
                EndpointKind::Handler(endpoint) => endpoint,
                EndpointKind::Help => Arc::new(HelpEndpoint::<S> {
                    catalog: Arc::clone(&catalog),
                    _state: PhantomData,
                }),
            };
            match definition.selector {
                Selector::Event { event_type, kind } => {
                    output.push(Arc::new(ModuleHandler {
                        spec: RouteSpec::Event(event_type),
                        event_kind: kind,
                        scope: definition.scope,
                        endpoint,
                        guards: definition.guards.into(),
                        before: definition.before.into(),
                        after: definition.after.into(),
                        command: None,
                        default_block: definition.default_block,
                    }));
                }
                Selector::Interaction(custom_id) => {
                    output.push(Arc::new(ModuleHandler {
                        spec: RouteSpec::Interaction(custom_id),
                        event_kind: DispatchKind::Interaction,
                        scope: definition.scope,
                        endpoint,
                        guards: definition.guards.into(),
                        before: definition.before.into(),
                        after: definition.after.into(),
                        command: None,
                        default_block: definition.default_block,
                    }));
                }
                Selector::Native(kind) => {
                    output.push(Arc::new(ModuleHandler {
                        spec: RouteSpec::Native(kind),
                        event_kind: DispatchKind::Native,
                        scope: definition.scope,
                        endpoint,
                        guards: definition.guards.into(),
                        before: definition.before.into(),
                        after: definition.after.into(),
                        command: None,
                        default_block: definition.default_block,
                    }));
                }
                Selector::Command(command) => {
                    command.validate().map_err(BuildError::InvalidRoute)?;
                    let specs = command.fast_route_keys().map_or_else(
                        || vec![RouteSpec::Event(EventType::Message)],
                        |keys| keys.into_iter().map(RouteSpec::Command).collect(),
                    );
                    for spec in specs {
                        output.push(Arc::new(ModuleHandler {
                            spec,
                            event_kind: DispatchKind::Message,
                            scope: definition.scope.clone(),
                            endpoint: Arc::clone(&endpoint),
                            guards: definition.guards.clone().into(),
                            before: definition.before.clone().into(),
                            after: definition.after.clone().into(),
                            command: Some(command.clone()),
                            default_block: definition.default_block,
                        }));
                    }
                    output.push(Arc::new(ModuleHandler {
                        spec: RouteSpec::Event(EventType::Interaction),
                        event_kind: DispatchKind::Interaction,
                        scope: definition.scope,
                        endpoint,
                        guards: definition.guards.into(),
                        before: definition.before.into(),
                        after: definition.after.into(),
                        command: Some(command),
                        default_block: definition.default_block,
                    }));
                }
            }
        }
        if !catalog.commands().is_empty() {
            output.push(Arc::new(ModuleHandler {
                spec: RouteSpec::Event(EventType::LifecycleSuggestionRequested),
                event_kind: EventType::LifecycleSuggestionRequested.dispatch_kind(),
                scope: RouteScope::global(),
                endpoint: Arc::new(SuggestionEndpoint::<S> {
                    catalog,
                    _state: PhantomData,
                }),
                guards: Arc::from([]),
                before: Arc::from([]),
                after: Arc::from([]),
                command: None,
                default_block: true,
            }));
        }
        Ok(output)
    }

    fn restrict_scope(&mut self, restriction: &RouteScope) {
        for handler in &mut self.handlers {
            match handler.scope.intersect(restriction) {
                Ok(scope) => handler.scope = scope,
                Err(error) => self.scope_errors.push(error),
            }
        }
        match self.default_scope.intersect(restriction) {
            Ok(scope) => self.default_scope = scope,
            Err(error) => self.scope_errors.push(error),
        }
    }

    fn bake_hooks(&mut self) {
        if self.guards.is_empty() && self.before.is_empty() && self.after.is_empty() {
            return;
        }
        for handler in &mut self.handlers {
            if !self.guards.is_empty() {
                let mut guards = self.guards.clone();
                guards.append(&mut handler.guards);
                handler.guards = guards;
            }
            if !self.before.is_empty() {
                let mut before = self.before.clone();
                before.append(&mut handler.before);
                handler.before = before;
            }
            if !self.after.is_empty() {
                handler.after.extend(self.after.iter().cloned());
            }
        }
        self.guards.clear();
        self.before.clear();
        self.after.clear();
    }
}

fn validate_command_conflicts<S>(handlers: &[HandlerDefinition<S>]) -> Result<(), String>
where
    S: Send + Sync + 'static,
{
    let commands = handlers.iter().filter_map(|handler| {
        let Selector::Command(command) = &handler.selector else {
            return None;
        };
        Some((command, &handler.scope))
    });

    let mut globals = HashMap::<Arc<str>, Arc<str>>::new();
    let mut platforms = HashMap::<(PlatformId, Arc<str>), Arc<str>>::new();
    let mut bots = HashMap::<(BotIdentity, Arc<str>), Arc<str>>::new();
    let commands = commands.collect::<Vec<_>>();
    for (command, _) in &commands {
        command.validate()?;
    }

    for (command, _scope) in commands
        .iter()
        .copied()
        .filter(|(_, scope)| scope.is_global())
    {
        for key in command.registration_keys() {
            if let Some(previous) = globals.insert(key.clone(), Arc::from(command.name())) {
                return Err(format!(
                    "command `{}` conflicts with `{previous}` in the global Bot scope",
                    command.name(),
                ));
            }
        }
    }

    for (command, scope) in commands
        .iter()
        .copied()
        .filter(|(_, scope)| scope.bot.is_none() && scope.platform.is_some())
    {
        let platform = scope
            .platform
            .as_ref()
            .expect("platform-scoped command has a platform");
        for key in command.registration_keys() {
            if let Some(previous) = globals.get(&key) {
                return Err(format!(
                    "command `{}` for platform {platform} conflicts with global command `{previous}`",
                    command.name(),
                ));
            }
            let map_key = (platform.clone(), key);
            if let Some(previous) = platforms.insert(map_key, Arc::from(command.name())) {
                return Err(format!(
                    "command `{}` conflicts with `{previous}` for platform {platform}",
                    command.name(),
                ));
            }
        }
    }

    for (command, scope) in commands
        .iter()
        .copied()
        .filter(|(_, scope)| scope.bot.is_some())
    {
        let bot = scope.bot.as_ref().expect("bot-scoped command has a bot");
        for key in command.registration_keys() {
            if let Some(previous) = globals.get(&key) {
                return Err(format!(
                    "command `{}` for bot {}:{} conflicts with global command `{previous}`",
                    command.name(),
                    bot.platform,
                    bot.bot,
                ));
            }
            if let Some(previous) = platforms.get(&(bot.platform.clone(), key.clone())) {
                return Err(format!(
                    "command `{}` for bot {}:{} conflicts with platform command `{previous}`",
                    command.name(),
                    bot.platform,
                    bot.bot,
                ));
            }
            let map_key = (bot.clone(), key);
            if let Some(previous) = bots.insert(map_key, Arc::from(command.name())) {
                return Err(format!(
                    "command `{}` conflicts with `{previous}` for bot {}:{}",
                    command.name(),
                    bot.platform,
                    bot.bot,
                ));
            }
        }
    }

    Ok(())
}

// Command selectors are stored once per handler; keeping commands inline avoids
// an allocation on every registration.
#[allow(clippy::large_enum_variant)]
enum Selector {
    Event {
        event_type: EventType,
        kind: DispatchKind,
    },
    Command(Command),
    Interaction(Arc<str>),
    Native(Arc<str>),
}

enum EndpointKind<S>
where
    S: Send + Sync + 'static,
{
    Handler(Arc<dyn Endpoint<S>>),
    Help,
}

struct HandlerDefinition<S>
where
    S: Send + Sync + 'static,
{
    selector: Selector,
    endpoint: EndpointKind<S>,
    guards: Vec<SharedGuard<S>>,
    before: Vec<SharedBefore<S>>,
    after: Vec<SharedAfter<S>>,
    scope: RouteScope,
    default_block: bool,
}

struct ModuleHandler<S>
where
    S: Send + Sync + 'static,
{
    spec: RouteSpec,
    event_kind: DispatchKind,
    scope: RouteScope,
    endpoint: Arc<dyn Endpoint<S>>,
    guards: Arc<[SharedGuard<S>]>,
    before: Arc<[SharedBefore<S>]>,
    after: Arc<[SharedAfter<S>]>,
    command: Option<Command>,
    default_block: bool,
}

impl<S> ErasedHandler<S> for ModuleHandler<S>
where
    S: Send + Sync + 'static,
{
    fn route_spec(&self) -> RouteSpec {
        self.spec.clone()
    }

    fn route_scope(&self) -> RouteScope {
        self.scope.clone()
    }

    fn event_kind(&self) -> DispatchKind {
        self.event_kind
    }

    fn default_block(&self) -> bool {
        self.default_block
    }

    fn call(
        &self,
        event: Arc<DispatchEnvelope>,
        state: Arc<S>,
        bot: BotHandle,
        sessions: SessionRegistry,
        shutdown: ShutdownSignal,
    ) -> BoxFuture<'static, HandlerResult<Outcome>> {
        let endpoint = Arc::clone(&self.endpoint);
        let guards = Arc::clone(&self.guards);
        let before = Arc::clone(&self.before);
        let after = Arc::clone(&self.after);
        let command = self.command.clone();

        Box::pin(async move {
            let command = if let Some(command) = command {
                match match_command_event(&command, event.event()) {
                    Ok(Some(result)) => Some(result),
                    Ok(None) => return Ok(Outcome::continue_()),
                    Err(error) => {
                        return Ok(command_parse_outcome(
                            &command,
                            &[],
                            error,
                            event_locale(event.event()),
                        ));
                    }
                }
            } else {
                None
            };

            let mut context = Context::new(event, state, bot, sessions, shutdown, command);

            // Admission runs before interactive completion. An unauthorized or
            // rate-limited user must never be prompted for missing arguments.
            for guard in guards.iter() {
                match guard.check(context.clone()).await? {
                    GuardDecision::Allow => {}
                    GuardDecision::Skip => return Ok(Outcome::continue_()),
                    GuardDecision::Deny(outcome) => {
                        return Ok(outcome.with_propagation(crate::Propagation::Stop));
                    }
                }
            }

            if context.command().is_some() {
                match prepare_command(context).await? {
                    CommandPreparation::Ready(ready) => context = ready,
                    CommandPreparation::Respond(outcome) => return Ok(outcome),
                }
            }
            for hook in before.iter() {
                hook.call(context.clone()).await?;
            }

            let mut outcome = endpoint.call(context.clone()).await?;
            for hook in after.iter() {
                outcome = hook.call(context.clone(), outcome).await?;
            }
            Ok(outcome)
        })
    }
}

struct HelpEndpoint<S>
where
    S: Send + Sync + 'static,
{
    catalog: Arc<CommandCatalog>,
    _state: PhantomData<fn() -> S>,
}

impl<S> Endpoint<S> for HelpEndpoint<S>
where
    S: Send + Sync + 'static,
{
    fn call(&self, context: Context<S>) -> BoxFuture<'static, HandlerResult<Outcome>> {
        let catalog = self.catalog.for_identity(context.bot_identity());
        let query = context
            .command()
            .map(|command| command.text_values().collect::<Vec<_>>().join(" "))
            .filter(|query| !query.is_empty());
        let locale = context
            .command()
            .and_then(CommandResult::locale)
            .map(ToOwned::to_owned)
            .or_else(|| event_locale(context.event()).map(ToOwned::to_owned));
        Box::pin(async move {
            Ok(Outcome::new().reply(catalog.render_message(query.as_deref(), locale.as_deref())))
        })
    }
}

struct SuggestionEndpoint<S>
where
    S: Send + Sync + 'static,
{
    catalog: Arc<CommandCatalog>,
    _state: PhantomData<fn() -> S>,
}

impl<S> Endpoint<S> for SuggestionEndpoint<S>
where
    S: Send + Sync + 'static,
{
    fn call(&self, context: Context<S>) -> BoxFuture<'static, HandlerResult<Outcome>> {
        let catalog = self.catalog.for_identity(context.bot_identity());
        Box::pin(async move {
            let Event::LifecycleEvent(oxidebot_core::event::LifecycleEvent::SuggestionRequested(
                request,
            )) = context.event()
            else {
                return Ok(Outcome::continue_());
            };
            let request = request.clone();
            let suggestions = catalog.native_suggestions(&request);
            context
                .bot()?
                .answer_suggestion_request(request, suggestions, None)
                .await
                .map_err(|error| HandlerError::Api(error.to_string()))?;
            Ok(Outcome::stop())
        })
    }
}

// The ready context is consumed immediately by the dispatcher, so boxing it
// would add an allocation to every successfully prepared command.
#[allow(clippy::large_enum_variant)]
enum CommandPreparation<S>
where
    S: Send + Sync + 'static,
{
    Ready(Context<S>),
    Respond(Outcome),
}

async fn prepare_command<S>(mut context: Context<S>) -> Result<CommandPreparation<S>, HandlerError>
where
    S: Send + Sync + 'static,
{
    let Some(mut result) = context.command().cloned() else {
        return Ok(CommandPreparation::Ready(context));
    };

    match result.parse_active() {
        Ok(arguments) => {
            context.command = Some(result.with_parsed(arguments));
            return Ok(CommandPreparation::Ready(context));
        }
        Err(error) if error.missing_prompt().is_none() => {
            return Ok(CommandPreparation::Respond(command_match_error_outcome(
                &result, error,
            )));
        }
        Err(error)
            if result.completion_ref().is_none()
                || matches!(result.source(), crate::CommandSource::Native(_)) =>
        {
            return Ok(CommandPreparation::Respond(command_match_error_outcome(
                &result, error,
            )));
        }
        Err(_) => {}
    }

    let completion = result
        .completion_ref()
        .cloned()
        .expect("missing arguments reach completion only when it is configured");
    let dialogue = Dialogue::extract(&context)?
        .timeout(completion.timeout)
        .namespace(format!(
            "command:{:016x}:{}",
            result.command().id().0,
            result
                .branch_path()
                .last()
                .map_or(0, |branch| u64::from(branch.0))
        ))?;

    for _ in 0..completion.max_rounds {
        let error = match result.parse_active() {
            Ok(arguments) => {
                context.command = Some(result.with_parsed(arguments));
                return Ok(CommandPreparation::Ready(context));
            }
            Err(error) => error,
        };
        let Some(prompt) = error.missing_prompt() else {
            return Ok(CommandPreparation::Respond(command_match_error_outcome(
                &result, error,
            )));
        };
        let missing_name = error
            .missing_name()
            .expect("a missing prompt always belongs to a missing argument")
            .to_owned();
        let response = dialogue.ask_message(prompt).await?;
        let Event::MessageEvent(message) = response.event() else {
            return Err(HandlerError::internal(
                "command completion received a non-message event",
            ));
        };
        let raw_text = message.message.get_raw_text();
        if completion.is_cancelled(&raw_text) {
            return Ok(CommandPreparation::Respond(command_match_error_outcome(
                &result,
                CommandParseError::Cancelled,
            )));
        }
        let values = match tokenize_segments(&message.message.segments) {
            Ok(values) => values,
            Err(error) => {
                return Ok(CommandPreparation::Respond(command_match_error_outcome(
                    &result, error,
                )));
            }
        };
        result = result.with_answer(&missing_name, values);
    }

    match result.parse_active() {
        Ok(arguments) => {
            context.command = Some(result.with_parsed(arguments));
            Ok(CommandPreparation::Ready(context))
        }
        Err(error) if error.missing_prompt().is_some() => Ok(CommandPreparation::Respond(
            command_match_error_outcome(&result, CommandParseError::CompletionExhausted),
        )),
        Err(error) => Ok(CommandPreparation::Respond(command_match_error_outcome(
            &result, error,
        ))),
    }
}

fn match_command_event(
    command: &Command,
    event: &Event,
) -> Result<Option<CommandResult>, CommandParseError> {
    match event {
        Event::MessageEvent(message) => command.match_event(message),
        Event::InteractionEvent(interaction)
            if interaction.kind == InteractionKind::Command && interaction.command.is_some() =>
        {
            command.match_invocation(
                interaction
                    .command
                    .as_ref()
                    .expect("guarded interaction command exists"),
            )
        }
        _ => Ok(None),
    }
}

fn event_locale(event: &Event) -> Option<&str> {
    match event {
        Event::InteractionEvent(interaction) => interaction
            .command
            .as_ref()
            .and_then(|command| command.locale.as_deref())
            .or(interaction.locale.as_deref()),
        _ => None,
    }
}

fn command_match_error_outcome(result: &CommandResult, error: CommandParseError) -> Outcome {
    command_parse_outcome(
        result.command(),
        result.branch_names(),
        error,
        result.locale(),
    )
}

fn command_parse_outcome(
    command: &Command,
    branch_names: &[Arc<str>],
    error: CommandParseError,
    locale: Option<&str>,
) -> Outcome {
    let output = CommandOutput::ParseError {
        command: command.clone(),
        branch_names: branch_names.to_vec().into(),
        error,
    };
    Outcome::stop().reply(DefaultCommandRenderer.render(&output, locale))
}
