//! Flat module and feature authoring model types.

use super::*;

/// A flat, reusable Bot feature module.
///
/// A module groups commands, event handlers, guards, and lifecycle hooks. It is
/// deliberately not a URL tree: multi-word commands are declared as ordinary
/// command names, and including another module never creates hidden nesting.
pub struct Module<S = ()>
where
    S: Send + Sync + 'static,
{
    pub(in crate::module) handlers: Vec<HandlerDefinition<S>>,
    pub(in crate::module) guards: Vec<SharedGuard<S>>,
    pub(in crate::module) before: Vec<SharedBefore<S>>,
    pub(in crate::module) after: Vec<SharedAfter<S>>,
    pub(in crate::module) default_scope: RouteScope,
    pub(in crate::module) scope_errors: Vec<String>,
    pub(in crate::module) has_help: bool,
    pub(in crate::module) runtime_shortcuts: bool,
    pub(in crate::module) overlays: Vec<crate::CommandOverlay>,
    pub(in crate::module) completers:
        HashMap<(CommandId, CommandFieldId), Arc<dyn DynamicCompleter<S>>>,
}

/// One Bot feature with all of its local configuration kept together.
///
/// A feature represents one command, event, interaction, or native handler plus
/// its local guards, hooks, scope, propagation behavior, shortcuts, and dynamic
/// completion providers. It is not a nested router.
pub struct Feature<S = ()>
where
    S: Send + Sync + 'static,
{
    pub(in crate::module) definition: HandlerDefinition<S>,
    pub(in crate::module) completers: Vec<CompleterBinding<S>>,
    pub(in crate::module) errors: Vec<String>,
    pub(in crate::module) runtime_shortcuts: bool,
}

pub(in crate::module) struct CompleterBinding<S>
where
    S: Send + Sync + 'static,
{
    pub(in crate::module) command: crate::CommandId,
    pub(in crate::module) field: crate::CommandFieldId,
    pub(in crate::module) provider: Arc<dyn DynamicCompleter<S>>,
}

/// A generated or manually configured capability that can be installed into a
/// flat [`Module`].
pub trait IntoFeature<S>: Sized
where
    S: Send + Sync + 'static,
{
    /// Installs this feature into `module`.
    fn install(self, module: Module<S>) -> Module<S>;
}

/// Implemented by values generated by `#[oxidebot::command]`.
///
/// It exposes the configurable one-handler feature before installation, while
/// [`IntoFeature`] remains the common installation protocol used by
/// [`Module::add`].
pub trait GeneratedFeature<S>: IntoFeature<S>
where
    S: Send + Sync + 'static,
{
    /// Converts the generated value into its configurable single-handler feature.
    fn into_feature(self) -> Feature<S>;
}

/// Local configuration shortcuts for generated command feature values.
pub trait FeatureExt: Sized {
    /// Adds a guard to a generated feature.
    fn guard<S, G>(self, guard: G) -> Feature<S>
    where
        S: Send + Sync + 'static,
        Self: GeneratedFeature<S>,
        G: Guard<S>,
    {
        self.into_feature().guard(guard)
    }

    /// Adds a before hook to a generated feature.
    fn before<S, B>(self, hook: B) -> Feature<S>
    where
        S: Send + Sync + 'static,
        Self: GeneratedFeature<S>,
        B: Before<S>,
    {
        self.into_feature().before(hook)
    }

    /// Adds an after hook to a generated feature.
    fn after<S, A>(self, hook: A) -> Feature<S>
    where
        S: Send + Sync + 'static,
        Self: GeneratedFeature<S>,
        A: After<S>,
    {
        self.into_feature().after(hook)
    }

    /// Restricts a generated feature to one platform.
    fn for_platform<S>(self, platform: PlatformId) -> Feature<S>
    where
        S: Send + Sync + 'static,
        Self: GeneratedFeature<S>,
    {
        self.into_feature().for_platform(platform)
    }

    /// Restricts a generated feature to one bot.
    fn for_bot<S>(self, bot: BotIdentity) -> Feature<S>
    where
        S: Send + Sync + 'static,
        Self: GeneratedFeature<S>,
    {
        self.into_feature().for_bot(bot)
    }

    /// Sets whether this generated feature stops matching after success.
    fn block<S>(self, block: bool) -> Feature<S>
    where
        S: Send + Sync + 'static,
        Self: GeneratedFeature<S>,
    {
        self.into_feature().block(block)
    }

    /// Lets matching continue after this generated feature succeeds.
    fn continue_after<S>(self) -> Feature<S>
    where
        S: Send + Sync + 'static,
        Self: GeneratedFeature<S>,
    {
        self.into_feature().continue_after()
    }

    /// Stops matching after this generated feature succeeds.
    fn stop_after<S>(self) -> Feature<S>
    where
        S: Send + Sync + 'static,
        Self: GeneratedFeature<S>,
    {
        self.into_feature().stop_after()
    }

    /// Adds a static command shortcut to a generated command feature.
    fn shortcut<S>(self, shortcut: Shortcut) -> Feature<S>
    where
        S: Send + Sync + 'static,
        Self: GeneratedFeature<S>,
    {
        self.into_feature().shortcut(shortcut)
    }

    /// Enables runtime shortcuts for a generated command feature.
    fn runtime_shortcuts<S>(self) -> Feature<S>
    where
        S: Send + Sync + 'static,
        Self: GeneratedFeature<S>,
    {
        self.into_feature().runtime_shortcuts()
    }

    /// Adds declarative completion metadata to a generated command feature.
    fn completion<S>(self, completion: CompletionConfig) -> Feature<S>
    where
        S: Send + Sync + 'static,
        Self: GeneratedFeature<S>,
    {
        self.into_feature().completion(completion)
    }

    /// Attaches a dynamic completion provider to a generated command field.
    fn complete<S, F, C>(self, field: F, provider: C) -> Feature<S>
    where
        S: Send + Sync + 'static,
        Self: GeneratedFeature<S>,
        F: CommandFieldTag,
        C: DynamicCompleter<S>,
    {
        self.into_feature().complete(field, provider)
    }
}

impl<T> FeatureExt for T {}
