[package]
name = "oxidebot-macros"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Derive macros for OxideBot's ergonomic command API"

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
proc-macro-crate.workspace = true
quote.workspace = true
syn.workspace = true

[dev-dependencies]
oxidebot-runtime = { path = "../oxidebot-runtime", version = "1.0.0" }
trybuild.workspace = true
