[package]
name = "oxidebot-console-example"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
oxidebot = { path = "../../crates/oxidebot", version = "1.0.0-alpha.1", features = ["multi-thread"] }
oxidebot-adapter-console = { path = "../../crates/oxidebot-adapter-console", version = "1.0.0-alpha.1" }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
