[package]
name = "oxidebot"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
description = "A high-performance, platform-neutral chatbot framework"
readme = "../../README.md"
keywords = ["bot", "chatbot", "async", "framework"]
categories = ["asynchronous", "api-bindings"]

[features]
default = ["signal"]
signal = ["oxidebot-runtime/signal"]
multi-thread = ["oxidebot-runtime/multi-thread"]

[dependencies]
oxidebot-core = { path = "../oxidebot-core", version = "1.0.0" }
oxidebot-macros = { path = "../oxidebot-macros", version = "1.0.0" }
oxidebot-runtime = { path = "../oxidebot-runtime", version = "1.0.0", default-features = false }
